### ISSUE TITLE
Change Theme Button is hidden on Medium screen

### ISSUE THREAD

**Issue by mohdhaider07** [girlscript/gssoc-website-new#100]
The Navbar on large screens has a Change Theme Button, and the hero section also has one when screen size is small. However, the Change Theme Button is hidden on medium-sized screens. The Change Theme Button is neither present in the Navbar nor in the hero section on medium-sized screens.

![image](https://github.com/girlscript/gssoc-website-new/assets/86488954/88ca42b5-4dfb-4680-a728-c2239820e4e4)

**Comment by mohdhaider07** [comment]
I want to work on this issue, please assign this to me

**Comment by mohdhaider07** [comment]
@nawed2611 Can I directly make PR?

**Comment by nawed2611** [comment]
Sure, go ahead!

**Comment by mohdhaider07** [comment]
@nawed2611  I had made PR #103 Regarding this issue please review that

**Comment by Suvraneel** [comment]
@mohdhaider07   Please make the requested changes. :octocat:

**Comment by mohdhaider07** [comment]
@Suvraneel please review PR again

**Comment by Aman-Manwani** [comment]
@Suvraneel Please assign me this issue

**Comment by Aman-Manwani** [comment]
@mohdhaider07 Are you still working on this issue??

**Comment by mohdhaider07** [comment]
> @mohdhaider07 Are you still working on this issue??

Yes. I was busy so I was not able to make PR

**Comment by Aman-Manwani** [comment]
If you are still busy, then can I do this ?

**Comment by Aman-Manwani** [comment]
@mohdhaider07 ok bro good luck 👍

**Comment by Aman-Manwani** [comment]
@mohdhaider07 are you going to make PR after gssoc ends ??
