### ISSUE TITLE
No alt attribute provided

### ISSUE THREAD

**Issue by payalpm** [girlscript/gssoc-website-new#102]
![GS_Foundation_logo_Black](https://github.com/girlscript/gssoc-website-new/assets/76490207/8d934635-3372-4639-a248-9eb08820538b)

**Comment by mhdamaan79** [comment]
Hi @Suvraneel, I want to work on this issue. Could you please assign it to me?

**Comment by payalpm** [comment]
Ya sure

**Comment by payalpm** [comment]
Done.
