### ISSUE TITLE
Randomize Project cards 

### ISSUE THREAD

**Issue by shobhitexe** [girlscript/gssoc-website-new#109]
![image](https://github.com/girlscript/gssoc-website-new/assets/29349136/f646872e-6287-4e7d-b3b5-72a74b2ab4b4)

As seen in above image whenever someone visits the project section it shows the project cards in same serial for every users 
we can randomize the cards placement on every render so the cards at bottom also gets better exposure 

What you guys think ?
if yes you can assign this to me 
Thanks

**Comment by Suvraneel** [comment]
@shobhitexe Very cool idea. I had thought about this but dint get time to go about it.

Go for it

**Comment by shobhitexe** [comment]
> @shobhitexe Very cool idea. I had thought about this but dint get time to go about it.
> 
> Go for it.
> 
> Also, please change only those lines in diff that need to be changed.

Sure have opened a PR #113 plz review it Thanks
