### ISSUE TITLE
Mistake in the schedule of gssoc

### ISSUE THREAD

**Issue by 1Shubham7** [girlscript/gssoc-website-new#111]
There is a mistake in the schedule of gssoc 2023. 

![issue](https://github.com/girlscript/gssoc-website-new/assets/116020663/341a1fc3-910f-45fa-800e-4ea0690f34f0)

Here 20th June is coming before 20th May, It actually should be 20th May because results were announced on 20th May.

**Comment by Suvraneel** [comment]
@1Shubham7  
GO FOR IT 🚀 

Its an image. You can find the assets here:
https://www.figma.com/file/aXL6autoWxlLLqLyYTTLVB/GSSoC-Website?node-id=0%3A1

**Comment by 1Shubham7** [comment]
@Suvraneel thank you for assigning me this issue. The figma file you shared is of GSSoC'22 not GSSoC'23. Also it is set to "view only' so I can't make changes.

**Comment by Suvraneel** [comment]
@1Shubham7  I know. We made the prototype last year. You're supposed to make a clone of that file for working on it.

![image](https://github.com/girlscript/gssoc-website-new/assets/63473496/e90b1ff0-930f-4094-82be-0102ffcc6f55)

**Comment by 1Shubham7** [comment]
Ok. Got it. I will quickly get the work done.

**Comment by 1Shubham7** [comment]
@Suvraneel . for that I will need to know when the leaderboard start . Is it 10th june?

**Comment by Suvraneel** [comment]
20th June ie, one month from start of contribution phase

**Comment by 1Shubham7** [comment]
ok. Thank you . Actually the 2022 schedule was different from this year. But I changed it accordingly.
![deone](https://github.com/girlscript/gssoc-website-new/assets/116020663/002a2ed7-181c-435d-80ad-143224db7a36)
I comppleted the change. Now what to do?

**Comment by Suvraneel** [comment]
make a PR... changing the website code

**Comment by 1Shubham7** [comment]
Yes but how can you please explain? you told me its an image, how can I change website code for the image. 
https://www.figma.com/file/eWTNVBrUhK8uONReDUJwu0/GSSoC-project?type=design&node-id=0-1&t=Dme5GpuoYg03TGLh-0
This is the link of updated figma file

**Comment by 1Shubham7** [comment]
I know how to do PRs, I have done about 100 PRs but I don't get how to get this change from figma to the code.
