### ISSUE TITLE
Issue: Add a search option to filter projects by name

### ISSUE THREAD

**Issue by Kalyan-velu** [girlscript/gssoc-website-new#112]
Description: On the GSSoC website, there is a project section where users can view GSSoC projects but there is no search option to filter projects by name. Currently, users can only filter projects by tech stack, which is not very convenient if they want to find a specific project. It would be nice to have a search bar or a dropdown menu where users can enter or select a project name and see the relevant information.

Expected behavior: When a user visits the project section of the GSSoC website, they should be able to search projects by name.

Actual behavior: There is no search option to filter projects by name on the project section of the GSSoC website. Users can only search projects by tech stack.

Steps to reproduce: Visit https://gssoc.girlscript.tech/project and observe the project section.

**Comment by Suvraneel** [comment]
@Kalyan-velu  Filter by tech stack is the most requested feature by newbie contributors... As for project names, Ctrl+F works.

Anyway, would love to see the UI you're proposing before assigning you. I mean if it doesn't look too confusing, we can add it

**Comment by Kalyan-velu** [comment]
I think you are right there is no need for this.😅
