### ISSUE TITLE
Unresponsive NavBar

### ISSUE THREAD

**Issue by Aman-Manwani** [girlscript/gssoc-website-new#117]
Navbar is not responsive in the middle size screens
![Screenshot 2023-06-11 124313](https://github.com/girlscript/gssoc-website-new/assets/104587833/26f31bde-28ae-40d8-9cc5-ea88c3d02294)

**Comment by Suvraneel** [comment]
@Aman-Manwani  The Navbar is responsive. The social floats are not.
![image](https://github.com/girlscript/gssoc-website-new/assets/63473496/2e622e0d-8737-4589-8e41-bf837411ae8c)

Lemme know if you have anything in mind
