### ISSUE TITLE
Enhancement: Make cursor as pointer on hovering over Team cards 

### ISSUE THREAD

**Issue by MisterMickey** [girlscript/gssoc-website-new#127]
I want to make an enhancement in gssoc website that when user hover over the TEAM member cards the the cursor should change to pointer.
![Screenshot from 2023-06-20 00-45-51](https://github.com/girlscript/gssoc-website-new/assets/93720428/43067cd3-0645-4395-950f-1c5813f40e88)

# Kindly assign me this issue under gssoc23

**Comment by Suvraneel** [comment]
@MisterMickey Aight sure. Go ahead!
