### ISSUE TITLE
Bug Fix: DataCamp image Resource not loading

### ISSUE THREAD

**Issue by MisterMickey** [girlscript/gssoc-website-new#129]
In sponsors section, DataCamp logo is not loading I'll find the reason and resolve it.

Kindly Assign me this issue under gssoc23

![Screenshot from 2023-06-21 15-39-36](https://github.com/girlscript/gssoc-website-new/assets/93720428/cd169b5d-06a6-4a68-bcb5-d375309bbc9a)
![Screenshot from 2023-06-21 15-39-27](https://github.com/girlscript/gssoc-website-new/assets/93720428/f064b3cf-6247-4b26-8b74-2d5465680915)

**Comment by MisterMickey** [comment]
@Suvraneel Kindly assign me this issue.

**Comment by Suvraneel** [comment]
@MisterMickey  We're actually gonna repopulate this with new sponsors

CC: @nawed2611 / @gurjeetsinghvirdee
