### ISSUE TITLE
Fix the team members photo link

### ISSUE THREAD

**Issue by MisterMickey** [girlscript/gssoc-website-new#132]
Some photos are not being loaded properly, I wanna fix this issue under gssoc23

![Screenshot from 2023-06-22 23-47-36](https://github.com/girlscript/gssoc-website-new/assets/93720428/e1202ce9-06df-499a-8614-896ce4bfa7e9)

**Comment by Suvraneel** [comment]
Can't reproduce this issue.
I mean its all loading for me.

![image](https://github.com/girlscript/gssoc-website-new/assets/63473496/6e9219ce-edcf-4346-b171-7df197b688fd)

However, I'm open to detection of new bugs, if any...
So, could you elaborate how you plan on fixing this issue (as well as what is causing this on your end)?

**Comment by MisterMickey** [comment]
@Suvraneel If It's loading on your end then maybe my internet has some issues & not gssoc website.

**Comment by MisterMickey** [comment]
Thanks for replying.
