### ISSUE TITLE
feat: add tags for better search 

### ISSUE THREAD

**Issue by shobhitexe** [girlscript/gssoc-website-new#133]
I believe the existing search functionality is effective, 
but it would greatly enhance user experience if additional tags were implemented. 
These tags would allow users to filter results with a single tap, making it easier to identify the various categories of projects available. 
The current search system can sometimes be challenging when trying to determine the different project classifications.

ex Tags like : React , Python , AI , Express etc....

![image](https://github.com/girlscript/gssoc-website-new/assets/29349136/b408e838-3021-4480-afad-104c480a9a4f)

**Comment by Suvraneel** [comment]
@shobhitexe Hey Shobhit, I have in fact implemented tags since last year (ie, if you click on any of those tags inside a project, it'll filter only the projects with those tags...)

If you do have a better UI idea or a different perspective I'll be very happy to assign you. Please drop a screenshot of prototype or rough sketch of what you're suggesting...

**Comment by shobhitexe** [comment]
> @shobhitexe Hey Shobhit, I have in fact implemented tags since last year (ie, if you click on any of those tags inside a project, it'll filter only the projects with those tags...) I'll need a lil more clarification about what you're suggesting If you do have a better UI idea or a different perspective I'll be very happy to assign you. Please drop a screenshot of prototype or rough sketch of what you're suggesting...

Something like this 

![Screenshot 2023-06-29 131854](https://github.com/girlscript/gssoc-website-new/assets/29349136/4f117128-1881-435c-896a-d469cc347237)

**Comment by Suvraneel** [comment]
@shobhitexe 
Seems cool.

GO FOR IT. 

Sure, do one or two such lines, whichever looks cooler.
Also, do maintain the color palette both both light and dark modes.
