### ISSUE TITLE
[Enhancement] : Fixing FAQ section

### ISSUE THREAD

**Issue by dishamodi0910** [girlscript/gssoc-website-new#136]
![image](https://github.com/girlscript/gssoc-website-new/assets/106090499/32cb56a5-0c45-41b6-b13b-234686908af5)

Hiding the answer of the previous one as soon as the next question is opened.

**Comment by Suvraneel** [comment]
@dishamodi0910  Nice observation. 
Assigning this one as well... :octocat:

**Comment by KDHARANIPRIYA** [comment]
Assign me this, I could fix this up!

**Comment by Melvin0070** [comment]
Hey can you assign me this issue?

**Comment by sanjay-kv** [comment]
@gurjeetsinghvirdee Thanks for suggetions, Do you know how the leaderboard system works on website. Our current team has some doubts with it.

**Comment by gurjeetsinghvirdee** [comment]
@sanjay-kv 

Create a separate sheet for all the projects you selected for 2024, ensuring that all the details remain the same. Then convert it to an OpenSheet as it will fetch all the project details from this sheet. Here, we are using the GitHub API to collect information about labels we are assigned. Currently, we are using `gssoc,` but you can change it if needed, perhaps using **uppercase.**

I believe someone has already starred that backend repository. The function is to generate a leaderboard by fetching the project details from the sheet and the labels from the GitHub API. Simply deploy the backend part, maybe on Render, and then add that URL to the website's leaderboard.js page. This will directly fetch the details from the backend to the website. The server runs twice a day, and it takes around 10-15 minutes to update the leaderboard on the main website.

When the program ends, generate it for the last time, then add all the data to a new file named `leaderboard24.json` Finally, replace the deployed URL with this `leaderboard24.json` file URL.
