### ISSUE TITLE
Enhancements to pages under More for GSSoC 2024 :octocat:

### ISSUE THREAD

**Issue by sanjay-kv** [girlscript/gssoc-website-new#161]
For GSSoC 2024, enhancing the "More" pages could significantly improve user experience and engagement. Here are some suggestions:

- By incorporating these enhancements, the "More" pages can become a comprehensive hub for participants to access resources, connect with the community, and make the most out of their GSSoC 2024 experience.
![Event Timeline 2024](https://github.com/girlscript/gssoc-website-new/assets/30715153/060a6ebd-a263-467d-bdf2-184c894fdd36)

**Comment by sanjay-kv** [comment]
These are the changes required for the same
- [ ] Change the Timeline to GSSOc'24
- [ ] Update the Registration link
- [ ] Replace GSSoC23 to 24
- [ ] Job Fair page - Make Changes @HemantKr071

**Comment by HemantKr071** [comment]
Done Sir ✔

**Comment by sanjay-kv** [comment]
Task 1: @HemantKr071 
![image](https://github.com/girlscript/gssoc-website-new/assets/30715153/41b44502-8fda-45ff-ab0c-97af257449dd)

Change this to 2023, Somehow we missed this and accidentally changed to 2023.

Task 2: These Highlighted Button needs to change
![image](https://github.com/girlscript/gssoc-website-new/assets/30715153/60c6e556-cda4-4b9f-a35b-a851695c4308)

Explore Button: redirect to --> https://www.girlscript.tech/home
Contact Us button --> https://www.linkedin.com/company/girlscriptsoc/about/?viewAsMember=true
Girl script India Summit --> https://www.linkedin.com/company/gssummit2021/?originalSubdomain=in

We will eventually change the Links latter. For time being this should be there.

**Comment by HemantKr071** [comment]
All the Redirecting Links are fixed now.
