### ISSUE TITLE
Updates to Teams & FAQ Page for GSSoC'24

### ISSUE THREAD

**Issue by sanjay-kv** [girlscript/gssoc-website-new#167]
The below are the updates required for this Issue.  @hustler0109 

- [x] Update team members' list with roles and bios.
- [x] Ensure contact information is up to date for communication.
- [x] Organize teams alphabetically or by project category for easy navigation.
- [x] Make sure The Head people come first as per last year
- [x] Include a call to action to encourage visitor involvement. (optional)

Link to Team details & Resource: https://github.com/orgs/GSSoC24/discussions/39

**Comment by sanjay-kv** [comment]
![WhatsApp Image 2024-04-22 at 21 36 09_5147bd6a](https://github.com/girlscript/gssoc-website-new/assets/30715153/8304d479-6006-4776-8617-4dccc304206f)

In the Mobile, Webpage works differently. Need to work on the drop-down layout.

**Comment by sanjay-kv** [comment]
Update the team Page with new member details. @Princegupta101 

Details can be found here: (2 new people) 

Need to copy the above image to this folder before making changes.: https://github.com/GSSoC24/.github/tree/main/assets

**Comment by sanjay-kv** [comment]
Update to FAQ @kpriyanshu2003

**Comment by sanjay-kv** [comment]
Team Page Updates: @HemantKr071 
Need to update the Profile photo of Sanjay KV, Aishal gupta

 1: The above-mentioned people's photos can be found here: https://github.com/GSSoC24/alumni/discussions/2
 2: Add the photos to the asset folder with the naming convention. 
 3: Update kpriyanshu2003 and nehal profile with links including the above photo updates. once they update.

**Comment by sanjay-kv** [comment]
Remove Subroto Banerjee (Sponsership) from gssoc website @HemantKr071

**Comment by sanjay-kv** [comment]
@HemantKr071 Is this done

**Comment by HemantKr071** [comment]
> @HemantKr071 Is this done

Sir , Facing some error and I am trying to resolve that. I will update you once it's done.

**Comment by HemantKr071** [comment]
> @HemantKr071 Is this done

Done Sir
