### ISSUE TITLE
Bug: image not loading on homepage

### ISSUE THREAD

**Issue by himanshu007-creator** [girlscript/gssoc-website-new#18]
refer <a href="https://gssoc.girlscript.tech/">here</a>.
The hero image at top and the image below it are not loading at all and the second image is also missing an alt tab

**Comment by Suvraneel** [comment]
@himanshu007-creator  Thanks for letting us now...  💯 
They are replacing the site is a work in progress... The web dev is transferring assets currently.
will fix right away
