### ISSUE TITLE
UI/UX Enhancement to the Contact us page

### ISSUE THREAD

**Issue by sanjay-kv** [girlscript/gssoc-website-new#185]
Go through the existing design and see the space to improve and come back with redesign or suggestions: @GSSoC24/ui-ux
We need a Contact Us page so @nehal-5 your first task will be come with UI design for the Contact Us page.

Existing Figma Complete Design:
https://www.figma.com/file/aXL6autoWxlLLqLyYTTLVB/GSSoC-Website?node-id=0%3A1

Here is the Link to the website: https://gssoc.girlscript.tech/

Below is the Contact Us page link need to be changed
![image](https://github.com/GSSoC24/being-an-GSSoc24/assets/30715153/b680e9f5-fb14-4bdc-8a70-457287e6b2fe)

New Figma UI Design: 
Figma Link of Contact Us page : https://www.figma.com/file/DGAoMsyHrSJtJrRt8gothd/Contact-Us-GSsoc?type=design&node-id=0%3A1&mode=dev&t=WHuYFXpWVriQTqZ1-1

**Comment by sanjay-kv** [comment]
Figma Link for page view: 
https://www.figma.com/file/DGAoMsyHrSJtJrRt8gothd/Contact-Us-GSsoc?type=design&node id=0%3A1&mode=design&t=sX2rmzZMBht4KFbj-1

**Comment by kpriyanshu2003** [comment]
@nehal-5 
Suggest changes for phone view regarding the 'Contact Details' mentioned on the left. 
Make suitable changes in the Figma File

**Comment by sanjay-kv** [comment]
Just noted one more thing in the main Figma file every design had Black and White theme, as we run darkmode in the website.
We have to consider that as well in the design right @kpriyanshu2003 @nehal-5

**Comment by nehal-5** [comment]
Figma Link for contact us page in phone view: https://www.figma.com/file/DGAoMsyHrSJtJrRt8gothd/Contact-Us-GSsoc?type=design&node-id=0%3A1&mode=design&t=F9N79RrnPj36xwiy-1
@kpriyanshu2003

**Comment by nehal-5** [comment]
Contact us page dark theme done

**Comment by sanjay-kv** [comment]
@kpriyanshu2003 Could you take over the UI from here?

**Comment by kpriyanshu2003** [comment]
On it.

**Comment by kpriyanshu2003** [comment]
@nehal-5  Are the changes in the UI for contact us final or something more to change?

**Comment by sanjay-kv** [comment]
> @nehal-5 Are the changes in the UI for contact us final or something more to change?

It has completely done and I reviewed it.

**Comment by kpriyanshu2003** [comment]
@sanjay-kv Created a PR. UI is done from my side.

**Comment by sanjay-kv** [comment]
> @sanjay-kv Created a PR. UI is done from my side.

Merged it, Thanks :)

**Comment by sanjay-kv** [comment]
@Princegupta101  you can work on the backend where someone text and clicks on sent button, the mail is generated to gssoc@girlscript.tech

**Comment by kpriyanshu2003** [comment]
@sanjay-kv  Build is failing due to the use of `<img>` tags. Suggested use of `<Image>` tag. [See Logs](https://github.com/girlscript/gssoc-website-new/actions/runs/8904644867/job/24454220282)

**Comment by sanjay-kv** [comment]
Thanks for highlighting this issue. @Princegupta101

**Comment by sanjay-kv** [comment]
any update on the development @Princegupta101

**Comment by Princegupta101** [comment]
Done
