### ISSUE TITLE
UI/UX design changes for Explore Page GSSoC'24

### ISSUE THREAD

**Issue by sanjay-kv** [girlscript/gssoc-website-new#187]
Task: Go through the website you can note the line of improvement in the UI/UX and note all the things over here.
We can discuss this with the team later and make a change @nehal-5 

![WhatsApp Image 2024-04-29 at 22 47 11_4794de40](https://github.com/girlscript/gssoc-website-new/assets/30715153/46dcbec9-3721-4c1b-9893-ceb0229dbcb7)
1. Currently when you click on the explore button it redirects to LinkedIn.

- once the user clicks on the button the goal is that the user should able to know what happens with gssoc24, it can be events updates on twitter related to GSSoC or from LinkedIn or we can link any articles binds to GSSoC.

figma Link: https://www.figma.com/file/aXL6autoWxlLLqLyYTTLVB/GirlScript-Summer-of-Code?type=design&node-id=0-1&mode=design&t=Tr1qjkyCYRT6Z7SI-0

**Comment by nehal-5** [comment]
> Task: Go through the website you can note the line of improvement in the UI/UX and note all the things over here. We can discuss this with the team later and make a change @nehal-5
> 
> ![WhatsApp Image 2024-04-29 at 22 47 11_4794de40](https://private-user-images.githubusercontent.com/30715153/326442109-46dcbec9-3721-4c1b-9893-ceb0229dbcb7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0NjM2MzYsIm5iZiI6MTcxNDQ2MzMzNiwicGF0aCI6Ii8zMDcxNTE1My8zMjY0NDIxMDktNDZkY2JlYzktMzcyMS00YzFiLTk4OTMtY2ViMDIyOWRiY2I3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDMwVDA3NDg1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlNzA2YWJhZjExYmJhOWUzM2MzNWUwNzhhZjk5NmMzNzNhZWQ0Yjg2NGNhYmU1NjhmMzVhZjBkZTc3YTgzYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.deUgVAgZd_5kfsDpuh0AvLfPdvF5crIf-rouvAEerbg)
> 
> 1. Currently when you click on the explore button it redirects to LinkedIn.
> 
> * once the user clicks on the button the goal is that the user should able to know what happens with gssoc24, it can be events updates on twitter related to GSSoC or from LinkedIn or we can link any articles binds to GSSoC.
> 
> figma Link: https://www.figma.com/file/aXL6autoWxlLLqLyYTTLVB/GirlScript-Summer-of-Code?type=design&node-id=0-1&mode=design&t=Tr1qjkyCYRT6Z7SI-0

Figma Design Link for "Explore" : https://www.figma.com/file/DGAoMsyHrSJtJrRt8gothd/Contact-Us-GSsoc?type=design&node-id=0%3A1&mode=design&t=Xif2S4s933KU3BcH-1

@sanjay-kv

**Comment by sanjay-kv** [comment]
Any update on th UI Part @hustler0109 

UI Design was done 2 days back.

**Comment by hustler0109** [comment]
> Any update on the UI development Part @hustler0109
> 
> UI Design was done 2 days back.

Will update you by tom

**Comment by sanjay-kv** [comment]
where you able to build the UI

**Comment by hustler0109** [comment]
> where you able to build the UI

Nope but I am trying

**Comment by sanjay-kv** [comment]
Is it done @hustler0109

**Comment by hustler0109** [comment]
> Is it done @hustler0109

There were lot of problems in this coz Nehal and me both do not have figma premium and Dev mode only runs in Premium. I am discussing with Prince if he can do it.

**Comment by sanjay-kv** [comment]
@hustler0109 prince is already occupied with the task I assigned. 

Just trying to understand, why we need Figma premium to implement UI on website?

And why this issue not communicated well before here . 6days already passed.

**Comment by khAja13** [comment]
Any updates on this feature?

**Comment by sanjay-kv** [comment]
No @khAja13 , This went to stale after designing figma.

I asked regarding render to prev PM , once get replies we can resume the leaderboard. 
![image](https://github.com/girlscript/gssoc-website-new/assets/30715153/75b34a75-41b9-4bd2-ac11-114781f85c81)

**Comment by khAja13** [comment]
Sure
