### ISSUE TITLE
[Urgent] Updates to Project Page for GSSoC'24

### ISSUE THREAD

**Issue by sanjay-kv** [girlscript/gssoc-website-new#191]
Attached the list of project this year, can you create a project page for 2024 @kpriyanshu2003 

https://docs.google.com/spreadsheets/d/1Tr5lF8D3jq1f56COL_fOHzjTrLPa_AOu4KW5Ofmc3P8/edit?usp=sharing

- [x] Use the similar stack for this year
- [x] Lets add all the finalised project from the excel sheet. 
- [x] Improvements can be made later.

**Comment by kpriyanshu2003** [comment]
@sanjay-kv Requested access for the spreadsheet.

**Comment by sanjay-kv** [comment]
Given you the access

**Comment by kpriyanshu2003** [comment]
Please show a sample of how it needs to be done.

**Comment by sanjay-kv** [comment]
i will arrange a session tomorrow we can discuss there

**Comment by sanjay-kv** [comment]
@nehal-5  Refer the below 2022 form , we need to make the 2024 form like in this template. 
If any doubts contact me. Attached files the application we received for 2024.

2022 Form Template: https://docs.google.com/spreadsheets/d/1OC5gOWCpUrDXI8HAPEM9iOohoznBfAVF9d-rSMO7FXM/edit#gid=0

2024 Projects can be found here. 
[Project Shortlist GSSoC'24 (1).xlsx](https://github.com/girlscript/gssoc-website-new/files/15217654/Project.Shortlist.GSSoC.24.1.xlsx)


Make changes here: https://docs.google.com/spreadsheets/d/1JiqHjGyf43NNkou4PBe7WT4KEyueuFJct2p322nNMNw/edit?usp=sharing

**Comment by sanjay-kv** [comment]
Mentor Assign: https://docs.google.com/spreadsheets/d/1rZmXMaopECby48DOr6cX28AmoPnbrp3sPzm3blRkQcc/edit?usp=sharing

**Comment by sanjay-kv** [comment]
@kpriyanshu2003 You can start working on this. 
 Can you assign a random number to each mentors ID and Project ID. the upload data to website
https://docs.google.com/spreadsheets/d/1JiqHjGyf43NNkou4PBe7WT4KEyueuFJct2p322nNMNw/edit?usp=sharing

**Comment by nehal-5** [comment]
> @nehal-5 Can you assign a random number to each mentors ID and Project ID. the upload data to website https://docs.google.com/spreadsheets/d/1JiqHjGyf43NNkou4PBe7WT4KEyueuFJct2p322nNMNw/edit?usp=sharing
> 
> @kpriyanshu2003 You can start working on this.
> 
> Update to priyanhsu once you done with you work,

Done! @kpriyanshu2003 @sanjay-kv

**Comment by nehal-5** [comment]
Donee! @kpriyanshu2003

**Comment by sanjay-kv** [comment]
@kpriyanshu2003  We need to go projects go live EOD.

**Comment by sanjay-kv** [comment]
@Princegupta101  I removed 3 projects because repository link is not mentioned. 

![image](https://github.com/girlscript/gssoc-website-new/assets/30715153/f213f4b3-e68a-416f-bc9a-554041c4ef9d)

- [ ] Mobile view fix.

![WhatsApp Image 2024-05-09 at 13 02 29_57fb55fd](https://github.com/girlscript/gssoc-website-new/assets/30715153/035b322f-dc15-459b-9389-9628ac5d43e0)

- [ ] Heading not changing.
![WhatsApp Image 2024-05-09 at 13 42 53_35bb68c6](https://github.com/girlscript/gssoc-website-new/assets/30715153/d2ea6465-2db9-45fe-9f72-0541bda1f861)
