### ISSUE TITLE
[Urgent] Updates to the Event Page

### ISSUE THREAD

**Issue by sanjay-kv** [girlscript/gssoc-website-new#192]
Need to update the Events page with details of this year Event. https://gssoc.girlscript.tech/event

As of now only change the first one 
![image](https://github.com/girlscript/gssoc-website-new/assets/30715153/7debdd46-1230-4d66-be61-d8c285d7d171)

The below is the poster you need to update. 
![WhatsApp Image 2024-05-04 at 23 37 09_0228c05f](https://github.com/girlscript/gssoc-website-new/assets/30715153/2df7a26e-44bf-4e97-8670-0bac03e3596a)

**Comment by sanjay-kv** [comment]
Is it done @hustler0109

**Comment by hustler0109** [comment]
> Is it done @hustler0109

Will complete by today

**Comment by sanjay-kv** [comment]
This update was suppose to go live yesterday, it's my bad not communicated the deadline. 

Try to make necessary changes asap.
