### ISSUE TITLE
[Urgent] Update to the Leaderboard page for GSSoC'24

### ISSUE THREAD

**Issue by sanjay-kv** [girlscript/gssoc-website-new#193]
We need to update the leaderboard page for this year. 

Start working on the changes and gather requirements you need to make the necessary changes
@Princegupta101 @kpriyanshu2003

**Comment by kpriyanshu2003** [comment]
@sanjay-kv And how exactly to do that ?

**Comment by Princegupta101** [comment]
same 2023 type we need the data and  some logic changes

 "https://raw.githubusercontent.com/girlscript/gssoc-website-new/main/pages/api/leaderboard23.json"

**Comment by sanjay-kv** [comment]
Is it doable, data in the sense the github Id of contributor right, anything specific let me know. Do you think we should have meeting with the admin of webpage to know more about it r is it doable from our end. @Princegupta101

**Comment by Princegupta101** [comment]
Sir, I believe it would be beneficial for us to connect with the admin to ensure the correct logic. 
The leaderboard only updates when the data.json file is updated, meaning changes occur solely upon data refresh and not in real-time. 
This functionality is currently designed for the final leaderboard.

**Comment by sanjay-kv** [comment]
sure i will arrange a session with them soon.

**Comment by sanjay-kv** [comment]
![image](https://github.com/girlscript/gssoc-website-new/assets/30715153/74419348-5b75-43e4-bcb2-3ad8a8dcbcc6)

**Comment by sanjay-kv** [comment]
@gurjeetsinghvirdee Can i know how you hosted 2023 leaderboard, 

https://community.render.com/t/server-randomly-restarts/7124 we are facing server randomly restart issue due to free plan in render. any help appreciated.

**Comment by gurjeetsinghvirdee** [comment]
@sanjay-kv  We hosted on Render's free plan and scheduled a cron job to generate the leaderboard every 12 hours. However, we didn't caused any issues. You can try using [CircleCI](https://circleci.com/) or [Railway](https://railway.app/) instead.

**Comment by gurjeetsinghvirdee** [comment]
is your code generating leaderboard on local 👀? @sanjay-kv

**Comment by sanjay-kv** [comment]
Yes. @gurjeetsinghvirdee 
I had a glimpse of it @khAja13

**Comment by sanjay-kv** [comment]
@gurjeetsinghvirdee could you accept this request to install railway to repo.
cc: @khAja13 

![image](https://github.com/girlscript/gssoc-website-new/assets/30715153/b48489bb-d9a2-482d-9846-e18a905f08d6)

**Comment by sanjay-kv** [comment]
@gurjeetsinghvirdee I wonder how 2023 leaderboard still running, are you paid for the service or still using the same?

**Comment by sanjay-kv** [comment]
Thanks for the info. 
currently, we used railway as render changed pricing policy. I will talk with the core team.

![image](https://github.com/girlscript/gssoc-website-new/assets/30715153/299df11f-87b3-4ac5-9a20-de3301971c3e)

**Comment by gurjeetsinghvirdee** [comment]
Railway don't have free plans they removed it?

**Comment by gurjeetsinghvirdee** [comment]
okay take it why to take chance of stopping the leaderboard middle of nowhere

**Comment by gurjeetsinghvirdee** [comment]
By the way can you look into Project No. 33 & 34 they both are same

**Comment by sanjay-kv** [comment]
Team is checking free hosting service available if any, once it found we will move into there, else we will buy the service.

**Comment by Princegupta101** [comment]
For leaderboard server issue:
 
I would recommend adding a custom "server health check" in our code that prints health checks to the console. This custom health check should run every 14-15 minutes to prevent the server from going to sleep due to inactivity. The server will receive a health check request every 14 minutes, which will reset the inactivity timer.
@sanjay-kv
