### ISSUE TITLE
Event Page Update : GSSOC24

### ISSUE THREAD

**Issue by sanjay-kv** [girlscript/gssoc-website-new#201]
@kartikmehta18   ![Sanjay Viswanathan Event](https://github.com/girlscript/gssoc-website-new/assets/30715153/5db338cb-9650-49aa-8ead-b09aa48d6d32)

![WhatsApp Image 2024-05-07 at 23 46 15_08f2f30f](https://github.com/girlscript/gssoc-website-new/assets/30715153/9c6693d5-64fd-4e0e-b6bf-3823f131be9e)

Details of event can be found under youtube Description: 

https://www.youtube.com/@girlscriptfoundation45/streams

@hustler0109 

replace the below to 2 and add it over there. 

Try to embed the youtube link rather than image

**Comment by sanjay-kv** [comment]
I rejected review because of few reason. @hustler0109 

- [ ] Pull changes everytime you work, priyanshu was working on project tab and updated, but when I look at your repo the project tab was not available. It doesn't mean the work you did is wrong. same work pull the changes using 
- [ ] `git pull`
![image](https://github.com/girlscript/gssoc-website-new/assets/30715153/9d6e28ad-8a79-4133-8c19-64bbe2a8f849)


- [ ] Also make the following changes. 

![image](https://github.com/girlscript/gssoc-website-new/assets/30715153/5b885320-365e-45b5-a21f-2c724356710d)
Like the time line stuff on all post
![image](https://github.com/girlscript/gssoc-website-new/assets/30715153/8d2bbe3a-f7cc-422c-88d7-a324b3c756e3)

- [ ] Remove all 2022 tag on the event page. we will eventually change all the events for time being we will remove all 2022 text
![image](https://github.com/girlscript/gssoc-website-new/assets/30715153/4b2620b2-8380-423b-ac94-924dd625fa21)

**Comment by hustler0109** [comment]
Okay

**Comment by sanjay-kv** [comment]
Reassigning to @HemantKr071

**Comment by sanjay-kv** [comment]
https://www.youtube.com/watch?v=wtwVsHCsQSU&pp=ygUKZ2lybHNjcmlwdA%3D%3D

add this event below. @kartikmehta18

**Comment by kartikmehta18** [comment]
> https://www.youtube.com/watch?v=wtwVsHCsQSU&pp=ygUKZ2lybHNjcmlwdA%3D%3D
> 
> add this event below. @kartikmehta18

Ok sir

**Comment by Vyomrana02** [comment]
If no one is working on it @sanjay-kv can you assign this issue to me.

**Comment by kartikmehta18** [comment]
Sir as u mentioned I already working on this @sanjay-kv

**Comment by sanjay-kv** [comment]
Sorry i have to reassign this issue to @kartikmehta18 as he is already working on it. 

I have few works for you @Vyomrana02 

![image](https://github.com/girlscript/gssoc-website-new/assets/30715153/c993d7f2-b47f-4c58-acc8-8087115700c6)
I need you to change this into 
27000+ registration

17000+ participants

20+ countries
200+ institutions
205 + projects

make a new issue if needed @Vyomrana02
