### ISSUE TITLE
Fix wrong link in the footer image

### ISSUE THREAD

**Issue by aswinikalyan30** [girlscript/gssoc-website-new#203]
<img width="1223" alt="image" src="https://github.com/girlscript/gssoc-website-new/assets/76677408/f1358ec2-b2ac-49d7-9724-f32217a7da98">

**Comment by sanjay-kv** [comment]
Hi @aswinikalyan30 ,

You can work on this issue. Maybe redirect to this page: https://gssoc.girlscript.tech/contact

**Comment by aswinikalyan30** [comment]
Raised a PR - do check @sanjay-kv
