### ISSUE TITLE
Feat Add : Allow searching the projects by their name

### ISSUE THREAD

**Issue by kpriyanshu2003** [girlscript/gssoc-website-new#208]

**Comment by khAja13** [comment]
@kpriyanshu2003 Isn't this feature already implemented?

![image](https://github.com/girlscript/gssoc-website-new/assets/50286911/c9b9e2ae-77cc-4234-ad59-eb04575862f9)

**Comment by kpriyanshu2003** [comment]
@khAja13  Yes it is.
