### ISSUE TITLE
In About Section colour of button is not proper

### ISSUE THREAD

**Issue by kartikmehta18** [girlscript/gssoc-website-new#213]
In the About section, the color of the buttons for applying as a contributor, mentor, and organization is incorrect.
![Screenshot 2024-05-10 200626](https://github.com/girlscript/gssoc-website-new/assets/125860170/e51439cd-ed01-44d3-b4b5-664016d10892)

**Comment by masterboy376** [comment]
Hello @kartikmehta18, I have successfully set up the project on my local machine. I would like to work on this issue under gssoc.
I would make necessary front end changes to solve this one.
