### ISSUE TITLE
Change the color of project card 

### ISSUE THREAD

**Issue by AbhiDiva96** [girlscript/gssoc-website-new#217]
The background color of the project card is completedly black so it doesn't give a good view change it from black to rgb(13 15 36)

**Comment by Nkmeoo7** [comment]
Hey AbhiDiva,
it will very good if you explain your issue  more clearly by writting good .md file and some adding some images

**Comment by AbhiDiva96** [comment]
hey @sanjay-kv ,
I just added a PR , please review it.
