### ISSUE TITLE
Repetitive functions on Project.js

### ISSUE THREAD

**Issue by vinayak-vohra** [girlscript/gssoc-website-new#227]
Hey gssoc team, while going through the code for the project page I noticed 4 different functions that perform an almost identical task, namely setting the project data state for a particular year:
- `getProjects2024()` 
- `getProjects2023()` 
- `getProjects2022()` 
- `getProjects2021()` 

So I combined them into a single function, `getProjects(year)` by creating a dictionary of years and corresponding API links.

Furthermore, instead of writing the code for button 4 times (for years 2021-2024), I mapped it based on the dictionary keys, thereby improving the **readability** and **maintainabilty** of the code.

I will create a PR for this issue. Please feel free to review the code and provide any feedback or suggestions.

**Comment by sanjay-kv** [comment]
merged
