### ISSUE TITLE
Give badges according to some milestones

### ISSUE THREAD

**Issue by sanjay-kv** [girlscript/gssoc-website-new#230]
Planning to roll out badges on weekly basis based on the performance. 

![image](https://github.com/girlscript/gssoc-website-new/assets/30715153/2e18bc80-3e48-4f99-a34d-0dc5535c20d4)

![image](https://github.com/girlscript/gssoc-website-new/assets/30715153/96868684-2dab-48fe-8052-03c1b3755f33)

Badges
60 points
140 points
200 points
300 points 
500 points 
And so on

100 points- participation certi eligible
200 points- exceptional contributor
350+- outstanding contributor
Then Top 100 contributors
And top 10 contributors

Certificates will be rolled out once the program ends

But badges will be rolled out on weekly basis

Drive Link badge: https://drive.google.com/drive/folders/1PitmAGJ5YmczVXrVTEFlsThqktZlcMxn?usp=drive_link
sample badge
![WhatsApp Image 2024-05-12 at 21 25 11_a9212f8f](https://github.com/girlscript/gssoc-website-new/assets/30715153/fe310b9e-654e-4671-84cb-d010abfaa8ff)

**Comment by khAja13** [comment]
@sanjay-kv the badges will be rolled out based on PR's? Or on what basis?

**Comment by sanjay-kv** [comment]
Yes , based on Score board PR

**Comment by khAja13** [comment]
![image](https://github.com/girlscript/gssoc-website-new/assets/50286911/3c65fbdb-ba03-4c1f-b0ce-8087f710f055)

So, exactly which badge need to show here for every user?

**Comment by sanjay-kv** [comment]
A person who scores >60 points get the attached badge by default.

Look into this doc: https://docs.google.com/spreadsheets/d/173mtIGnZtVY0FjQsH6z7brZ9rNY6zSAYE1V-zk4fkUU/edit?usp=sharing

**Comment by sanjay-kv** [comment]
![image](https://github.com/girlscript/gssoc-website-new/assets/30715153/221eb355-1539-4d7e-975f-1b3855b5b541)

Explorer badge

**Comment by khAja13** [comment]
![image](https://github.com/girlscript/gssoc-website-new/assets/50286911/825cd4ce-f047-4a99-a468-00312c4bfcef)

**Comment by khAja13** [comment]
Do you also want me to show the tooltip on hovering on a badge?

**Comment by sanjay-kv** [comment]
Yes that would be great.

**Comment by khAja13** [comment]
![image](https://github.com/girlscript/gssoc-website-new/assets/50286911/748143e1-42e1-4cdc-839b-31754b0153e6)

Is it fine? @sanjay-kv

**Comment by sanjay-kv** [comment]
yes. its good. I think if the badge background removed it would be more UI friendly. Whats your thought. 

+if you available for 1:1 gmeet for 15 min, let me know. your work is great.

**Comment by khAja13** [comment]
Yup, we can connect now Sanjay.

**Comment by sanjay-kv** [comment]
I assigned you lables.

**Comment by sanjay-kv** [comment]
![image](https://github.com/girlscript/gssoc-website-new/assets/30715153/fb49303e-9fbe-4980-89bd-b9bc9f8d0a30)

@khAja13 Its the response from prev year team.

**Comment by khAja13** [comment]
We need the 2024 sheet details and also do we access to the 2023 backend code which was deployed in render?

**Comment by sanjay-kv** [comment]
I will get back you on this. @khAja13

**Comment by sanjay-kv** [comment]
@khAja13  this is the reply i got. 

there's a repo in same org named gssoc-leaderboard-backend. https://github.com/girlscript/gssoc22-leaderboard-backend
It's a simple Node app that runs a cron job & fetches via GitHub octokit api/sdk

json file was used to make the content static so that it dint update after program close

**Comment by sanjay-kv** [comment]
So they are not using json file they using the above repo to fetch the PR's

**Comment by khAja13** [comment]
Since all of the code base is there, then I think we just need to provide the Opensheet URL to it, where it has all the data

**Comment by khAja13** [comment]
Yup this is the sheet we needed

**Comment by sanjay-kv** [comment]
Please check if you can pull leaderboard of this year in local system. Then half of problem solved .

**Comment by khAja13** [comment]
Do you want me to create a new repo for 2024 leaderboard or let's use that same repo and do the changes needed?

**Comment by sanjay-kv** [comment]
Let's create new repo for 2024 .

**Comment by khAja13** [comment]
Can you tell me the exact gsoc label by which we need to search and also the date range of PR's which needs to be considered?

**Comment by sanjay-kv** [comment]
gssoc

level1,level2,level3

**Comment by khAja13** [comment]
so every repo has to have that **gssoc** label right?

**Comment by sanjay-kv** [comment]
yes

**Comment by khAja13** [comment]
But I see a repo where it has **GSSoC'24**, so with this we get empty results

**Comment by sanjay-kv** [comment]
can we include two labels, i see few repo used GSSoC'24 label.

**Comment by khAja13** [comment]
And the dates range which we are considering for PR's?

**Comment by sanjay-kv** [comment]
starting from 10th May 2024

**Comment by sanjay-kv** [comment]
@Princegupta101 I will be unavailble for next 7 hours, help @khAja13 with necessary information. Thanks.

**Comment by khAja13** [comment]
This is the 2024 leaderboard data(Backend): https://[512f-49-43-224-144.ngrok-free.app/OSLeaderboard](https://512f-49-43-224-144.ngrok-free.app/OSLeaderboard)

This is the frontend: https://b438-49-43-224-218.ngrok-free.app/leaderboard

**Comment by sanjay-kv** [comment]
Thanks. 

I believe we didnt pullled all data. Few of the contributors in my repo are missing. any idea for how to cross check it?

**Comment by sanjay-kv** [comment]
> Planning to roll out badges on weekly basis based on the performance.
> 
> ![image](https://private-user-images.githubusercontent.com/30715153/329948062-2e18bc80-3e48-4f99-a34d-0dc5535c20d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNjA3MzcsIm5iZiI6MTcxNjM2MDQzNywicGF0aCI6Ii8zMDcxNTE1My8zMjk5NDgwNjItMmUxOGJjODAtM2U0OC00Zjk5LWEzNGQtMGRjNTUzNWMyMGQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDA2NDcxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5M2E5ZmNlMjVhNGQ5NzRjMWYyOGI3NDYzMTM1ZmIzOWQ4NDYwZjY2YjE5YzQyOWY3ZWIxMWNhM2M1YjkyYzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QMUw6CuJZQzyPnpj6DqqAhi1SYq0V9WRRM9u8V1o6WI)
> 
> ![image](https://private-user-images.githubusercontent.com/30715153/329948164-96868684-2dab-48fe-8052-03c1b3755f33.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNjA3MzcsIm5iZiI6MTcxNjM2MDQzNywicGF0aCI6Ii8zMDcxNTE1My8zMjk5NDgxNjQtOTY4Njg2ODQtMmRhYi00OGZlLTgwNTItMDNjMWIzNzU1ZjMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDA2NDcxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwNTljZGM3ZDU0YWY5Y2YzMTBkZWRmMmM5Yjg2M2YxOTA3Y2YwNjRhNTczZjMzOWE2NWJhZGVkNjY0MmRhM2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jwAd26QJTzkLBubDBjDP65PzG2tlawm_qjBcRWQtWCs)
> 
> Badges 60 points 140 points 200 points 300 points 500 points  And so on
> 
> 100 points- participation certi eligible 200 points- exceptional contributor 350+- outstanding contributor Then Top 100 contributors And top 10 contributors
> 
> Certificates will be rolled out once the program ends
> 
> But badges will be rolled out on weekly basis
> 
> Drive Link badge: https://drive.google.com/drive/folders/1PitmAGJ5YmczVXrVTEFlsThqktZlcMxn?usp=drive_link sample badge ![WhatsApp Image 2024-05-12 at 21 25 11_a9212f8f](https://private-user-images.githubusercontent.com/30715153/329948512-fe310b9e-654e-4671-84cb-d010abfaa8ff.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNjA3MzcsIm5iZiI6MTcxNjM2MDQzNywicGF0aCI6Ii8zMDcxNTE1My8zMjk5NDg1MTItZmUzMTBiOWUtNjU0ZS00NjcxLTg0Y2ItZDAxMGFiZmFhOGZmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDA2NDcxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkMTdmMmNhYjgwMWM3NGMyN2FiOGRiNzQ2Zjk2ZjYxMzA4YThlNjg5NTM1MTlkM2YwODFiOWZlMzU4NmRhZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dPMAOGCFEuWOQhy0V3RsiMoxMUTDx-L4WQWPxPUSiyc)

@Princegupta101 There is the drive link , can you use this tool to remove all background of the badge

https://www.remove.bg/

**Comment by khAja13** [comment]
> Thanks.
> 
> I believe we didnt pullled all data. Few of the contributors in my repo are missing. any idea for how to cross check it?

Yes, we didn't pulled all data because the given project links are invalid. I do have some list of invalid project links and i did cross check and yes they are invalid. So if we can change in the given sheet itself then all of these things will be sorted.

**Comment by sanjay-kv** [comment]
@khAja13 I found out the issue.

Right now only fetching labels with gssoc, GSSOC24 or only GSSOC24

but we mainly focus on labels gssoc, so repo with only gssoc is not pulled here.

**Comment by khAja13** [comment]
> StackOverflow

![image](https://github.com/girlscript/gssoc-website-new/assets/50286911/b28e18a2-4827-4c16-abeb-28529b6a49b6)

This is how it will look if we remove bg and apply dark mode

**Comment by sanjay-kv** [comment]
thats not good. i will check withmy graphic team regarding updates.

**Comment by khAja13** [comment]
> @khAja13 I found out the issue.
> 
> Right now only fetching labels with gssoc, GSSOC24 or only GSSOC24
> 
> but we mainly focus on labels gssoc, so repo with only gssoc is not pulled here.

In that case give me all the possible labels...now I am fetching the issues with labels gssoc24,GSSoC'24 only

**Comment by sanjay-kv** [comment]
gssoc24,GSSoC'24, gssoc 

These are the labels. 

with level1,level2, level3

**Comment by khAja13** [comment]
> Thanks.
> 
> I believe we didnt pullled all data. Few of the contributors in my repo are missing. any idea for how to cross check it?

Can you tell me your repo details so that I can check?

**Comment by sanjay-kv** [comment]
https://github.com/Recode-Hive/Stackoverflow-Analysis

https://github.com/Recode-Hive/Scrape-ML

regarding those project not able to fetch I will check and update you.

**Comment by khAja13** [comment]
> https://github.com/Recode-Hive/Stackoverflow-Analysis
> 
> https://github.com/Recode-Hive/Scrape-ML
> 
> regarding those project not able to fetch I will check and update you.

Mostly those repo's names have been changed and some moved to other

**Comment by khAja13** [comment]
> Recode-Hive/Scrape-ML

After adding gssoc label (which I didn't added before) I was able to get the data of these 2 repos

**Comment by sanjay-kv** [comment]
Thanks, because i was only using gssoc labels. 

My graphics team is working on the logos I will get back with you on updates.

**Comment by sanjay-kv** [comment]
@khAja13 When you free can i get simillar frontend with updated gssoc labels. 

I want to see how many people made into leaderboard.

**Comment by sanjay-kv** [comment]
I need one more suggetion, there are few people spamming I just figured it out by looking at the leaderboard. 

They just made documentation and got level2 and score is high. How can we reduce to one point and normalize it.  @khAja13 @Princegupta101 @kpriyanshu2003 

![image](https://github.com/girlscript/gssoc-website-new/assets/30715153/12843d37-b24a-420e-a875-f18462f2cb43)

**Comment by khAja13** [comment]
I think the person who assigns the issues has to verify that where are they spamming the PR's or not

**Comment by sanjay-kv** [comment]
The new badge icons can be found here: https://drive.google.com/file/d/1TfBxT9FLE4X6IRqYIZ3u5hp5ZyuNgRfV/view?usp=drive_link


https://docs.google.com/spreadsheets/d/173mtIGnZtVY0FjQsH6z7brZ9rNY6zSAYE1V-zk4fkUU/edit?usp=sharing

names is still updating.

**Comment by khAja13** [comment]
Let me know once all the names are updated, I will update it and also change all those badges which won't be visible properly in dark mode.

label0 in the codebase? You mean in the leaderboard backend codebase?

**Comment by sanjay-kv** [comment]
yes sorry its not label0, its level0 in the backend codebase.

**Comment by khAja13** [comment]
No @sanjay-kv we are only having level1, level2, level3

**Comment by sanjay-kv** [comment]
![image](https://github.com/girlscript/gssoc-website-new/assets/30715153/f7c2b993-7a0f-4134-946b-10ae364c374a)


can you add badges to here as well, its badge collection area. if user score is 1000 he might have earned 3 badges or something, so all will come here. 

+ please send your email ID. I will send some perks for making this big changes and helping us.

**Comment by khAja13** [comment]
@sanjay-kv  Please check this and let me know whether is this the expected one or not...!!

![image](https://github.com/girlscript/gssoc-website-new/assets/50286911/4e795516-5a8d-40b4-8cb4-d7e9b73c475b)

**Comment by sanjay-kv** [comment]
![image](https://github.com/girlscript/gssoc-website-new/assets/30715153/a82ec735-47d6-44af-ba07-514b9d3df805)

Looks good maybe if we can change the layout to this side would be great. Updated logo is available on the link I provided u above .

**Comment by khAja13** [comment]
I will change the width and all

![image](https://github.com/girlscript/gssoc-website-new/assets/50286911/8dc81dd6-9348-4456-82cc-36f809e42620)

Yaah i see only badge there, but we need all the badges which looks fine in both light and dark modes

**Comment by sanjay-kv** [comment]
Here is the new badge links

https://drive.google.com/drive/folders/1n6FBpzwPSaOkoBYnnG11jfbpJYXfFTGX

**Comment by khAja13** [comment]
@sanjay-kv what do you think about this?

![image](https://github.com/girlscript/gssoc-website-new/assets/50286911/7b657c96-6f68-4a14-b911-839303e25141)

**Comment by sanjay-kv** [comment]
![image](https://github.com/girlscript/gssoc-website-new/assets/30715153/b8295c3f-93e9-49f5-83a4-6d63cdd1d97e)


I like the placement here comparing the above one. 

![WhatsApp Image 2024-05-23 at 20 31 54_1cc0b272](https://github.com/girlscript/gssoc-website-new/assets/30715153/913e2f46-11ae-4918-8137-b2e90e39b6b0)


can you try the above in the darkmode

**Comment by khAja13** [comment]
This image will look weird in light mode and is this fine
 
 
![image](https://github.com/girlscript/gssoc-website-new/assets/50286911/998c9c0d-351a-4100-9fe1-a57552a0d860)

**Comment by sanjay-kv** [comment]
Looks fine. 

I know the below highlighted image size is different that's why it look small compare to others. can we change size on backend so all look identical . 
![image](https://github.com/girlscript/gssoc-website-new/assets/30715153/78de30d6-166d-42b2-b885-6d34a02cfcac)

**Comment by khAja13** [comment]
I have made all of those images of same size, it's just the image

**Comment by sanjay-kv** [comment]
> I have made all of those images of same size, it's just the image

I will talk to graphics team to change that

**Comment by khAja13** [comment]
> can we revert back to your intial placement. That look much clear.
> 
> sporry about the confusion. ![image](https://private-user-images.githubusercontent.com/30715153/333168080-9e018077-4357-44ec-a264-3d3730b53db4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NjQ5NTMsIm5iZiI6MTcxNjQ2NDY1MywicGF0aCI6Ii8zMDcxNTE1My8zMzMxNjgwODAtOWUwMTgwNzctNDM1Ny00NGVjLWEyNjQtM2QzNzMwYjUzZGI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDExNDQxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5YjE0YWZjZmJhNzdlZTllNjc1MzRkY2VkMzMxZTYzZWE3MTVkNWJiOWRlMWZmMDcyMjMxYzE1NTQxMzQxMjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3seOiT5ba2p9fuxvylB_4SO9uyePSPvsnGX36qtlzvE)

Okay reverting back

**Comment by khAja13** [comment]
![image](https://github.com/girlscript/gssoc-website-new/assets/50286911/bbd75320-0434-4dcd-b9f5-3e453fdde8ef)

Can you check now?

**Comment by khAja13** [comment]
And where do you want me to host the backend?

**Comment by sanjay-kv** [comment]
can we have a quick 1:1 Meeting?

**Comment by khAja13** [comment]
Sure

**Comment by sanjay-kv** [comment]
https://meet.google.com/shz-ezsh-zyq
