### ISSUE TITLE
You guy's mistakely changed my text stack Of NEST ONDC

### ISSUE THREAD

**Issue by MAVRICK-1** [girlscript/gssoc-website-new#234]
This Rishi Mondal PA of NEST ONDC 

<img width="293" alt="Screenshot 2024-05-15 102431" src="https://github.com/girlscript/gssoc-website-new/assets/146999057/9466c098-358f-4e20-9bca-6a69ed565ef1">

 You guy's mistakely changed my text stack.
it was Reactjs, JavaScript , HTML , CSS , Firebase , OpenStreetMap

**Comment by MAVRICK-1** [comment]
@sanjay-kv

**Comment by sanjay-kv** [comment]
will rename it.

**Comment by Princegupta101** [comment]
Done @sanjay-kv @MAVRICK-1
