### ISSUE TITLE
[BUG] : Bubbling Of Navbar On Clicking Leaderboard

### ISSUE THREAD

**Issue by Harshit7492** [girlscript/gssoc-website-new#236]
### Description
Hovering over the leaderboard link causes an unintended bubble to appear in the navbar. This affects the user interface by adding an unexpected visual element.

### Steps to Reproduce
1. Navigate to the homepage.
2. Hover over the "LEADERBOARD" link in the navbar.
3. Observe the appearance of a bubble in the navbar.

### Expected Behavior
Hovering over the "LEADERBOARD" link should not produce any bubbles or unexpected visual elements. The link should simply change appearance as per the hover state styling.

### Actual Behavior
When hovering over the "LEADERBOARD" link, a bubble appears in the navbar, which is not part of the intended design.
### Screenshots
- Hover state showing the bubble (Actual): 
![Screenshot 2024-05-19 181638](https://github.com/girlscript/gssoc-website-new/assets/114082380/f32daec3-de13-4647-beb4-a1b57694af81)
### Video

https://github.com/girlscript/gssoc-website-new/assets/114082380/5e6dd4f1-8695-4c05-a17c-9ba243bc3ee8

### Environment
- Browser: Chrome 90.0.4430.212
- Operating System: Windows 10

### Labels
`bug`, `frontend`, `UI`, `help wanted`

**Comment by Harshit7492** [comment]
I am @Harshit7492 . please assign me this issue I can resolve this bug @sanjay-kv 
I also fix some bugs in it 

## Screenshots
![Screenshot 2024-05-19 183609](https://github.com/girlscript/gssoc-website-new/assets/114082380/ee865bd8-115b-4634-8681-b51a76c8dec4)

**Comment by Harshit7492** [comment]
@sanjay-kv please review the code for issue #236

**Comment by sanjay-kv** [comment]
Sure I will do it today. Can I know you been part of gssoc this year contributor.

**Comment by sanjay-kv** [comment]
can i assign you few different issue which we are trying to solve.

**Comment by Harshit7492** [comment]
> can i assign you few different issue which we are trying to solve.

Ok @sanjay-kv you can assign me (@Harshit7492) new issues i try my best to solve them
