### ISSUE TITLE
Fixing Minor Issues

### ISSUE THREAD

**Issue by sanjay-kv** [girlscript/gssoc-website-new#239]
https://gssoc.girlscript.tech/info

you can see references to 2022 issues. need to fix it.

**Comment by Harshit7492** [comment]
> https://gssoc.girlscript.tech/info
> 
> you can see references to 2022 issues. need to fix it.

Please eleaborate @sanjay-kv  i not understand is issue . this is my first year open source contribution 2024

**Comment by sanjay-kv** [comment]
cha
