### ISSUE TITLE
Changing the stats

### ISSUE THREAD

**Issue by Vyomrana02** [girlscript/gssoc-website-new#241]
@sanjay-kv 
As Discussed in #240 
I need you to change this into
27000+ registration

17000+ participants

20+ countries
200+ institutions
205 + projects

Please assign it to me.

**Comment by sanjay-kv** [comment]
in js file i didnt see you changed 2023 to 2024

![image](https://github.com/girlscript/gssoc-website-new/assets/30715153/78f88cb6-dba1-431c-a97b-afa00ef6dc4d)


could you do that as well.
