### ISSUE TITLE
bug: UI bug with badges with score less than 60

### ISSUE THREAD

**Issue by dhairyathedev** [girlscript/gssoc-website-new#247]
### Issue 
Currently participants having score less than 60 breaks the badge image. To fix this issue we need to implement conditional rendering.

Please assign this issue to me, so that I can make a PR.

### Screenshot
<img width="1265" alt="Screenshot 2024-05-30 at 9 26 28 PM" src="https://github.com/girlscript/gssoc-website-new/assets/65452005/50f217b1-35ed-4683-985a-70716bc82325">

### Fix
<img width="1334" alt="Screenshot 2024-05-30 at 9 32 16 PM" src="https://github.com/girlscript/gssoc-website-new/assets/65452005/e94588bb-9925-481f-8925-141b93cac023">

**Comment by khAja13** [comment]
@sanjay-kv

**Comment by sanjay-kv** [comment]
This is alright, this will make people to contribute more and get badges.

@khAja13 could you remove hemu from blacklist and send PR for It. 

There are few issue in leaderboard, will discuss when you free.
