### ISSUE TITLE
Add details about the badge annoouncment

### ISSUE THREAD

**Issue by sanjay-kv** [girlscript/gssoc-website-new#251]
I would like to add details about the badge

![image](https://github.com/girlscript/gssoc-website-new/assets/30715153/b6be2f9f-f9cb-40cb-8713-1249ea84cbb3)

Leaderboard link: https://github.com/GSSoC24/Contributor/discussions/288

Text to add: More details about badges

**Comment by Hemu21** [comment]
@sanjay-kv  can you please assign this to me
