### ISSUE TITLE
[Feat]: Enhancement the LeaderBoard searchbar

### ISSUE THREAD

**Issue by SrinivasDevolper** [girlscript/gssoc-website-new#255]
The list should be filtered every time the user enters the value in search bar on leader board section

**Use:**
- The user doesn't need to enter his username completely in the search bar
- It is more user-friendly

**I am GSSOC24 Contributor
Please assign me, I would like to work on it**

**Comment by sanjay-kv** [comment]
added gssoc label, to avoid spam this repo wont be added until July end to leaderboard.
