### ISSUE TITLE
Issue with Project Tab: Default to 2024 instead 2021

### ISSUE THREAD

**Issue by sanjay-kv** [girlscript/gssoc-website-new#256]
By default if somebody enter to project tab , by default 2021 project is highlighted until the user click 2024. 

![image](https://github.com/girlscript/gssoc-website-new/assets/30715153/bb47a15e-1254-4e06-bb94-c166560c9dbc)

**Comment by vinayak-vohra** [comment]
Hey @sanjay-kv, can you elaborate? 
Because when I open the project tab, I see 2024 projects directly.

**Comment by sanjay-kv** [comment]
alright some people where complaining about it. I'm closing this issue.
