### ISSUE TITLE
Leaderboard Info updates: Gssoc 2024

### ISSUE THREAD

**Issue by sanjay-kv** [girlscript/gssoc-website-new#257]
Can we add more features like this? This helps more transparency in leaderboard ranking. @khAja13 

![image](https://github.com/girlscript/gssoc-website-new/assets/30715153/3c96a718-4a00-4fcc-a55e-728c678507b9)

**Comment by khAja13** [comment]
Yup, I think we can add this

**Comment by sanjay-kv** [comment]
It would be great, rn there is lot of confusion to people because of less information available on score board.

**Comment by n-keerthi-gayathri** [comment]
hi @sanjay-kv , can you assign me this issue, i want to give a try, i am GSSOC'24 Contributor

**Comment by Vyomrana02** [comment]
@sanjay-kv i have tried pull request 2 times but it's failing cause bo authority for changing some files.
