### ISSUE TITLE
Badge Email updates

### ISSUE THREAD

**Issue by sanjay-kv** [girlscript/gssoc-website-new#260]
sending automatic Mail to the user when they achieve each badge on leaderboard 

![image](https://github.com/girlscript/gssoc-website-new/assets/30715153/2df50ba7-0aaa-401b-ad89-748e012a3914)

**Comment by soubhik-111** [comment]
can you assign it to me

**Comment by sanjay-kv** [comment]
You can start working on it, I don't have laptop access , I will assign later today.

**Comment by sanjay-kv** [comment]
Hi @soubhik-111 How its going

**Comment by soubhik-111** [comment]
@sanjay-kv 
Its going good. I figured out 2 different ways and chosen the more optimized way, also I have started the implementation.

**Comment by sanjay-kv** [comment]
hows this going?
