### ISSUE TITLE
Chat system for the community.

### ISSUE THREAD

**Issue by mukilan2815** [girlscript/gssoc-website-new#262]
We can add a chat system where the participants can chat and if any beginners they can ask their doubt with this community.

**Comment by sanjay-kv** [comment]
any sample you can show me how it look like.

**Comment by mukilan2815** [comment]
![image](https://github.com/girlscript/gssoc-website-new/assets/71129858/e6cc9fef-7947-4cda-ac6c-57d814b1396c)

If user press that chat with community button , then user can chat in a common group where he can ask doubts and share other issues faced by them in gssoc. Instead of going to discord we can make a chatsystem here.

**Comment by sanjay-kv** [comment]
thats good.
