### ISSUE TITLE
Show more details on the project Page 

### ISSUE THREAD

**Issue by sanjay-kv** [girlscript/gssoc-website-new#264]
![image](https://github.com/girlscript/gssoc-website-new/assets/30715153/dc3e880d-f57d-4931-a117-9cb064f9a7cf)

Add more features like total open PR and issue to existing Project Page.

**Comment by Sid-80** [comment]
I am willing to work on this issue!

**Comment by sanjay-kv** [comment]
much appreciated @Sid-80

**Comment by Sid-80** [comment]
@sanjay-kv We are having any api for getting data about PRs.

**Comment by sanjay-kv** [comment]
i think we should already have in leaderboard.js file

**Comment by sanjay-kv** [comment]
Hows this going @Sid-80

**Comment by Sid-80** [comment]
@sanjay-kv I am out of station!! I will surely complete it!!

**Comment by Sid-80** [comment]
![image](https://github.com/girlscript/gssoc-website-new/assets/101277141/8c76a0bc-13d4-4737-89c2-9197436b3a59)

In leaderboard.json, we are having only user data. Here we need project events!!

**Comment by Sid-80** [comment]
UI is ready, just data is remaining

**Comment by Sid-80** [comment]
@sanjay-kv 
UI
![image](https://github.com/girlscript/gssoc-website-new/assets/101277141/a8e5354b-a756-4094-8572-23c64b6f13be)

**Comment by sanjay-kv** [comment]
@Sid-80 what you suggest new api just for projects?

**Comment by Sid-80** [comment]
Yess. The api should return the above required data about projects. Or Modification in projects api to add the above additional details like last PR merged, open issues, open PRs!!

**Comment by sanjay-kv** [comment]
I think modification in the existing project API will do, additional API calling will make the loading data slower. 
Let me know whether you can do it or you need any help

**Comment by Sid-80** [comment]
We can display the above info after clicking on project details modal. What's your view

**Comment by Sid-80** [comment]
Performance will not be affected

**Comment by sanjay-kv** [comment]
then we can create new API and link to it. Sorry about the delay in communications.

**Comment by Sid-80** [comment]
Yepp!! No issues!! Patience is imp in Open Source

**Comment by Sid-80** [comment]
Please guide me to create api !!

**Comment by Sid-80** [comment]
@sanjay-kv I have to use any backend endpoint ??

**Comment by sanjay-kv** [comment]
I will connect with person who is good at api. So can collaborate with him.

**Comment by Sid-80** [comment]
Let me know!! Thank you!!

**Comment by devXprite** [comment]
Hi @Sid-80,

I've created an API for the Projects Page, which allows you to retrieve all project details in a single API call. The data is automatically updated every hour, and the response time is super fast, so it won't slow down data loading.

If you want you use this API on the Projects Page. If you have any specific additional data you'd like to see in the API response, just let me know.

**API Endpoint:** [ https://gssoc-leaderboard.vercel.app/api/projects]( https://gssoc-leaderboard.vercel.app/api/projects)

### Example Response: 
![Screenshot at 2024-06-25 19-23-35](https://github.com/girlscript/gssoc-website-new/assets/80192140/5c066754-d675-44bb-a11c-69139c6a8fa2)

**Comment by Sid-80** [comment]
Hii @devXprite, 
totalPullRequests are total PRs merged or number of PRs open ?

**Comment by devXprite** [comment]
> Hii @devXprite, totalPullRequests are total PRs merged or number of PRs open ?

They are Open PR. I think i should Rename it to `openPullRequests` & `OpenIssues`.

**Comment by Sid-80** [comment]
Yepp!! Better for understanding

**Comment by sanjay-kv** [comment]
> > Hii @devXprite, totalPullRequests are total PRs merged or number of PRs open ?
> 
> 
> 
> They are Open PR. I think i should Rename it to `openPullRequests` & `openIssues`. 
> 
> 

Yes, that would easy to understand for future enhancement

**Comment by Sid-80** [comment]
I will give it a try!! Will ping if any backend error occurs

**Comment by devXprite** [comment]
> > > Hii @devXprite, totalPullRequests are total PRs merged or number of PRs open ?
> > 
> > 
> > They are Open PR. I think i should Rename it to `openPullRequests` & `openIssues`.
> 
> Yes, that would easy to understand for future enhancement

Done :+1:. Now Changes are live.

**Comment by Sid-80** [comment]
@devXprite CORS issue
![image](https://github.com/girlscript/gssoc-website-new/assets/101277141/4eaea5bf-20e9-4577-a819-18def094f72f)

**Comment by Sid-80** [comment]
![image](https://github.com/girlscript/gssoc-website-new/assets/101277141/a966be55-a50c-49a8-a2ef-8964c7c495c1)

@sanjay-kv I think scrollbar doesn't look better on cards. What's your view ?

**Comment by Sid-80** [comment]
@devXprite Which year's projects will be returned, latest one?

**Comment by devXprite** [comment]
> @devXprite CORS issue ![image](https://private-user-images.githubusercontent.com/101277141/342835012-4eaea5bf-20e9-4577-a819-18def094f72f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzODU2MDcsIm5iZiI6MTcxOTM4NTMwNywicGF0aCI6Ii8xMDEyNzcxNDEvMzQyODM1MDEyLTRlYWVhNWJmLTIwZTktNDU3Ny1hODE5LTE4ZGVmMDk0ZjcyZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNlQwNzAxNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOTJiM2FhMjFmY2Q4NmJiOTk5M2NiNDZkZjIwN2U4ZjVlNjQzYWQzOTc1NTI3MTRiNGFlN2IxNTc1OGJkNzkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QBU8c09IYMJri7E6fOJKLnkmFWWkd5QrIJPQ0Pfa4ME)

Fixed :+1:

**Comment by devXprite** [comment]
> @devXprite Which year's projects will be returned, latest one?

Yes, they are current year projects and are ordered by the most recent commit date.

**Comment by sanjay-kv** [comment]
> ![image](https://private-user-images.githubusercontent.com/101277141/342836034-a966be55-a50c-49a8-a2ef-8964c7c495c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0MzQzNjUsIm5iZiI6MTcxOTQzNDA2NSwicGF0aCI6Ii8xMDEyNzcxNDEvMzQyODM2MDM0LWE5NjZiZTU1LWE1MGMtNDlhOC1hMmVmLTg5NjRjN2M0OTVjMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNlQyMDM0MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMjQ5NmZmZGYwNGNiOTFiN2NmZjc0Mzk4MTQ3ZmE0N2I1N2M1NDUwOTY5MTc2NGVjOTk0ODNiYjM4NjU3MjlkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.32IasJDywFarquo0a_W2SjfaMgdUK8x5is5ijBkfWMk)
> 
> @sanjay-kv I think scrollbar doesn't look better on cards. What's your view ?

yes, we can create a standard size without scrolls
