### ISSUE TITLE
UI Development for Wob winter of blockchain

### ISSUE THREAD

**Issue by sanjay-kv** [girlscript/gssoc-website-new#266]
Requirements: Create a new Figma theme and add sowmiya to the project you creating, she will assist you.

Need a subpage for Web3 conf in existing gssoc website: https://gssoc.girlscript.tech/

add a new tab called Winter of blockchain

Step 2: When you click on that, it should take you to a new page. which is exactly similar to gssoc https://gssoc.girlscript.tech/, keep the components of UI the same as before..

Step 3: yeah we can have a different one too to differentiate it
you can check the poster colour scheme of wob in the girl script account black+violet

Step 4: we don't have previous history, so we can make it a fresh theme

**Comment by sanjay-kv** [comment]
Figma Link: https://www.figma.com/design/ctaIuB6yqKjzG7uXZyMEZg/GSSOC-WebsiteNEW?node-id=0-1&t=Iv6pU2iSZFrnRKBn-0

**Comment by Prithwi32** [comment]
@sanjay-kv I can collaborate to solve this issue..
Thank You!

**Comment by sanjay-kv** [comment]
@sowmiyeh will guide you on figma how to proceed and regarding the development requirements I mentioned above. 
Feel free to bring the creative ideas. @Prithwi32

**Comment by sanjay-kv** [comment]
@Prithwi32 @nehal-5 
https://www.figma.com/file/aXL6autoWxlLLqLyYTTLVB/GSSoC-Website?node-id=0%3A1

you can copy the entire design and paste it in this https://www.figma.com/design/ctaIuB6yqKjzG7uXZyMEZg/GSSOC-WebsiteNEW?node-id=0-1&t=Iv6pU2iSZFrnRKBn-0


so it would be easy for us to modify. 

Change 1: Light blue and white - represnts winter combo      - we are removing orange and black design 
Change 2: Title bar menu will have WoB now along with other tabs.

**Comment by sanjay-kv** [comment]
progress on development

UI/UX: 
- [X] Main Page
- [X] Teams Page
- [X] Leaderboard Page
- [X] Events Page
- [X] Project Page

Web Dev:
- [X] Main Page - Need some CR
- [X] Teams Page
- [X] Project Page
- [ ] Leaderboard Page
- [ ] Events Page

**Comment by Prithwi32** [comment]
> Progress on development
> 
> UI/UX:
> 
> * [x]  Main Page @nehal-5
> * [x]  Teams Page @Prithwi32
> * [x]  Leaderboard Page @Prithwi32
> * [x]  Events Page @nehal-5
> * [x]  Project Page @nehal-5
> 
> Web Dev:
> 
> * [x]  Main Page - Need some CR @Hemu21
> * [x]  Teams Page @Hemu21
> * [x]  Project Page @Hemu21
> * [ ]  Leaderboard Page
> * [ ]  Events Page

@sanjay-kv leaderboard and main page done by both, event page done by me

**Comment by sanjay-kv** [comment]
@Hemu21 
can you give us the video capture of all pages here. Team want to review it.

**Comment by Hemu21** [comment]
https://github.com/girlscript/gssoc-website-new/assets/106808387/0916a2f3-c96d-4642-b77f-0bda32168b3d

**Comment by sanjay-kv** [comment]
@sowmiyeh Please go through it. 
Uploading confirm.mp4…

**Comment by sowmiyeh** [comment]
Thanks to everyone who worked on this project. I'll be reviewing it soon and will let you know if I have any questions or need revisions.
