### ISSUE TITLE
Winter of Blockchain page in existing Gssoc Website. 

### ISSUE THREAD

**Issue by sanjay-kv** [girlscript/gssoc-website-new#270]
Requirements: Create the website based on Figma UI on winter of block chain.
Watch Video: https://www.loom.com/share/410dc1f3a3c54780a93d3de725de07ba?sid=a997b2a1-3c35-46c3-ae2d-16b965088551
Need a subpage for Web3 conf in existing gssoc website: https://gssoc.girlscript.tech/
add a new tab called Winter of blockchain

Step 2: When you click on that, it should take you to a new page. which is exactly similar to gssoc https://gssoc.girlscript.tech/, keep the components of UI the same as before..

Figma Link: https://www.figma.com/design/ctaIuB6yqKjzG7uXZyMEZg/GSSOC-WebsiteNEW?node-id=0-1&t=Iv6pU2iSZFrnRKBn-0

**Comment by Hemu21** [comment]
@sanjay-kv I want to on this.

**Comment by Hemu21** [comment]
@sanjay-kv  I doesn't get the figma access. mail: `gujjalahemanthkumar789@gmail.com`

**Comment by sanjay-kv** [comment]
sure
![image](https://github.com/girlscript/gssoc-website-new/assets/30715153/d966e624-5eae-4406-9488-a00fb6589d43)
i approved your request
