### ISSUE TITLE
Enhancments on Scroll-toTop Button Matching to Website's Design Theme

### ISSUE THREAD

**Issue by MastanSayyad** [girlscript/gssoc-website-new#271]
Hey @sanjay-kv 

The current scroll-to-top button looks little inconsistent due to size, color and shape

![image](https://github.com/girlscript/gssoc-website-new/assets/101971980/1ef59302-2cdc-4334-be2a-aae3a9bed426)

I would like to make Enhancments on Scroll-toTop Button Matching to Website's Design Theme, tho these are just minor changes I'm willing to do it.

![image](https://github.com/girlscript/gssoc-website-new/assets/101971980/06a0b321-2895-4be8-8a29-3307af5fe987)

**Comment by sanjay-kv** [comment]
this is awesome
