### ISSUE TITLE
change the UI of this form 

### ISSUE THREAD

**Issue by heli0707** [girlscript/gssoc-website-new#279]
![image](https://github.com/girlscript/gssoc-website-new/assets/95361125/00d089a3-fde0-4d3a-834e-acf44ab1a328)

make this UI better and something animated like below 

https://github.com/girlscript/gssoc-website-new/assets/95361125/a906c9c4-9b66-4e26-b9d0-69aa665812dc

assign this issue to me I will do it! 
GSSoC '24

**Comment by heli0707** [comment]
The issue has been closed, but I have not received any points. Why?Sent from Mail for Windows From: Sanjay ViswanathanSent: 30 June 2024 13:40To: girlscript/gssoc-website-newCc: Heli Detroja; AssignSubject: Re: [girlscript/gssoc-website-new] change the UI of this form (Issue #279) Closed #279 as completed via #304.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were assigned.Message ID: ***@***.***>

**Comment by sanjay-kv** [comment]
To avoid people spam, kept this project not listed . at the end of this month will add all the points.

**Comment by heli0707** [comment]
Ok thank you  Sent from Mail for Windows From: Sanjay ViswanathanSent: 01 July 2024 11:06To: girlscript/gssoc-website-newCc: Heli Detroja; AssignSubject: Re: [girlscript/gssoc-website-new] change the UI of this form (Issue #279) To avoid people spam, kept this project not listed . at the end of this month will add all the points.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were assigned.Message ID: ***@***.***>
