### ISSUE TITLE
Theme change option not there in mobile sccreen size

### ISSUE THREAD

**Issue by manikumarreddyu** [girlscript/gssoc-website-new#280]
<img width="191" alt="image" src="https://github.com/girlscript/gssoc-website-new/assets/133508962/e4a89747-03dd-4b37-ad1e-1e636f92d29c">
<img width="260" alt="image" src="https://github.com/girlscript/gssoc-website-new/assets/133508962/f86d2229-1d40-49d0-8b74-04b103cbfa81">

**Comment by manikumarreddyu** [comment]
> <img alt="image" width="191" src="https://private-user-images.githubusercontent.com/133508962/342656826-e4a89747-03dd-4b37-ad1e-1e636f92d29c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzMDY1MTksIm5iZiI6MTcxOTMwNjIxOSwicGF0aCI6Ii8xMzM1MDg5NjIvMzQyNjU2ODI2LWU0YTg5NzQ3LTAzZGQtNGIzNy1hZDFlLTFlNjM2ZjkyZDI5Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNVQwOTAzMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MGRmY2E0ZTk4MDNlOGQ0YTlhN2ZkYjBhMjg4ZDc5ZmY1MTllNTE4MGNmNWY3ZGNiOTRhZWYxMjU0N2ZlZGVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.y48cytDUo-fGjX2jeuoEc_gBqlHyiRYE4lTSZYgca5U"> <img alt="image" width="260" src="https://private-user-images.githubusercontent.com/133508962/342657454-f86d2229-1d40-49d0-8b74-04b103cbfa81.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzMDY1MTksIm5iZiI6MTcxOTMwNjIxOSwicGF0aCI6Ii8xMzM1MDg5NjIvMzQyNjU3NDU0LWY4NmQyMjI5LTFkNDAtNDlkMC04Yjc0LTA0YjEwM2NiZmE4MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNVQwOTAzMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYjE3ODg1MmU5Nzk5NTRmYTk1MzNmZjA5NDE4NzdiNWRlMTU5ZThkYzk2NzY5ZTBmMjBjZTM3NDMyNmNiM2QyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Ky4Qz6NxAGG4RN94C20GbTgQ823TiWc_jh10C_QPLPY">

i want to solve this issue
assign me under gssoc 2024

**Comment by sanjay-kv** [comment]
![WhatsApp Image 2024-06-27 at 07 04 07_4943b9ea](https://github.com/girlscript/gssoc-website-new/assets/30715153/76ef1a8a-7f08-4976-a03f-c520279d2445)

It's already there @manikumarreddyu
