### ISSUE TITLE
Making the pagination useful.

### ISSUE THREAD

**Issue by partha120804** [girlscript/gssoc-website-new#281]
We can add a copy of pagination on top of the table, so that you don't have to scroll down to change the page.
we can also add a button to change how many contributors they want on a page ( currently it is fixed to 50). We can add a drop down for 25,50,100,200,500,1000.
we can also make the bottom pagination bar automatically triggering "scroll to top" button.

I want to work under GSSOC24 to add this enhancement.

**Comment by sanjay-kv** [comment]
I think this will make some issue because we have around 2000 list. 
do you have an sample website to show me.

**Comment by partha120804** [comment]
I have already added this and it works perfectly, i am just working on how to refresh the page when the item count is changed (currently it is working only after changing page on pagination bar), i am kind of stuck.

**Comment by partha120804** [comment]
but it can only work smoothly till 200items per page, any greater number lags my local server, @sanjay-kv will the main server be able to handle it ??

**Comment by partha120804** [comment]
I am creating a PR please check if its working, its working fine on my device :) @sanjay-kv

**Comment by sanjay-kv** [comment]
Sure
