### ISSUE TITLE
Project Frame Issues: + Sorting Enhancment GSSOC :octocat: 

### ISSUE THREAD

**Issue by sanjay-kv** [girlscript/gssoc-website-new#289]
Need to remove the scroll on the projects tab + sorting kinda option based on open issue or open pull request. 

![image](https://github.com/girlscript/gssoc-website-new/assets/30715153/674fd2ef-eb9d-4886-825c-08c002057c93)

light mode theme changed:
It has been noticed after last PR light mode theme has been changed as well. 
below right shows previous theme: right side shows after the PR changes
![image](https://github.com/girlscript/gssoc-website-new/assets/30715153/7802b3ff-baf2-4d3e-b7de-d2dd119c8e28)

**Comment by devXprite** [comment]
@sanjay-kv I want to work on this issue

**Comment by Ayushmaanagarwal1211** [comment]
Sir if this issue is up for grabs  i want to work on that

**Comment by sanjay-kv** [comment]
sorry guys these developments have been already assigned.

**Comment by Suvraneel** [comment]
^ @devXprite Is this still being worked on?
If not pls reassign to someone.

PS. The extra texts such as last updated timestamp, open issues etc. make the Bento cards clumsy.
Either put icons to shorten it (should be intuitive tho), 
or if not possible move it inside the modal for progressive disclosure.

**Comment by devXprite** [comment]
I have resolved this issue in #294 , and project page will looks like [this](https://gssoc.devxprite.tech/projects). 

Although it works fine on my local machine, it throws an error in production. I need a deployment preview of that deploy to identify and fix that error.

**Comment by Suvraneel** [comment]
> I have resolved this issue in #294 , and project page will looks like [this](https://gssoc.devxprite.tech/projects).
> 
> Although it works fine on my local machine, it throws an error in production. I need a deployment preview of that deploy to identify and fix that error.

I see. Unfortunately vercel doesnt allow org repos to be deployed on their free tier. Pls take a fork of the repo & preview. I suppose that's the only way :feelsgood:

**Comment by devXprite** [comment]
> > I have resolved this issue in #294 , and project page will looks like [this](https://gssoc.devxprite.tech/projects).
> > Although it works fine on my local machine, it throws an error in production. I need a deployment preview of that deploy to identify and fix that error.
> 
> I see. Seems like a hydration error. Unfortunately vercel doesnt allow org repos to be deployed on their free tier. Pls take a fork of the repo & preview. I suppose that's the only way :feelsgood:

I fixed that hydration error and successfully deployed it on [Vercel](https://gssoc-website-new.vercel.app/project). So it shouldn't throw any errors now.

**Comment by sanjay-kv** [comment]
are you available to connect for 15 min on gmeet?
