### ISSUE TITLE
WoB: Main Page: Enhancement 

### ISSUE THREAD

**Issue by sanjay-kv** [girlscript/gssoc-website-new#290]
Add stat simillar to GSSOC: dummy one + some details 
![image](https://github.com/girlscript/gssoc-website-new/assets/30715153/9a6b90c8-c304-4b68-ba5a-d08a617547ff)

Home:

GirlScript Winter of blockchain is a 30 days long
Blockchain #OpenSource program by GirlScript Foundation.
10th July - 10th August 2024

add about section : I will add it later here, you can add dummy text.

**Comment by Hemu21** [comment]
@sanjay-kv  can you please assign me.
