### ISSUE TITLE
WoB: Favicon Updates & Logo

### ISSUE THREAD

**Issue by sanjay-kv** [girlscript/gssoc-website-new#291]
Parsha Please share the link of the SVG file here.

**Comment by sanjay-kv** [comment]
Canva File: https://www.canva.com/design/DAGIrIQ6FHE/RiNthCkQwQ1oG73cfRvyfg/edit?utm_content=DAGIrIQ6FHE&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Comment by sanjay-kv** [comment]
SVG Logo: https://drive.google.com/drive/folders/15M4nJnsj3mX9LyTM62OzU0NeVSLJ4nsG?usp=sharing

**Comment by Hemu21** [comment]
@sanjay-kv  can you please assign this to me
