### ISSUE TITLE
UI IMPROVEMENT: FAQs Page

### ISSUE THREAD

**Issue by sau-mili** [girlscript/gssoc-website-new#292]
The UI of the FAQs page is very common, generic. We can improve it with better CSS properties.
Kindly assign me this issue, so that I can work on this and contribute on this project.
N.B: I myself, am a GSSOC'24 contributor

**Comment by sanjay-kv** [comment]
i would be happy to assign you, I would like to know or see some sample you want to implement. 
https://gssoc.girlscript.tech/faq

you can list some sample and we can select best out of it.

**Comment by sau-mili** [comment]
Sure, I will be listing out some sample by tonight.

**Comment by sau-mili** [comment]
## Dark mode
![Screenshot 2024-06-28 215425](https://github.com/girlscript/gssoc-website-new/assets/146661411/644fabb1-1a58-4578-b6f7-b6e4d6d95dc3)
![Screenshot 2024-06-28 215436](https://github.com/girlscript/gssoc-website-new/assets/146661411/aa7dbb55-2be3-489b-9322-3f03f0f3c534)

## Light mode
![Screenshot 2024-06-28 215511](https://github.com/girlscript/gssoc-website-new/assets/146661411/4e5ddc0d-ba2c-43dd-9f0a-9234afe953b7)
![Screenshot 2024-06-28 215520](https://github.com/girlscript/gssoc-website-new/assets/146661411/1913e444-7677-45e6-ab12-231a0569edd1)

do you like this?

**Comment by Suvraneel** [comment]
@sau-mili 

Border 1 looks kinda cool.
Whichever @sanjay-kv approves, go for it.

But make sure it's responsive. 
(I did not make it responsive due to lack of time ig)
And yep, use Tailwind classes/modifiers only (for consistency)

**Comment by sau-mili** [comment]
okay!

**Comment by sanjay-kv** [comment]
@sau-mili 

I really appreciate this idea,  I did like border1
![image](https://github.com/girlscript/gssoc-website-new/assets/30715153/1e8f7cd3-2280-406d-97f7-61d3f607cf51)

Suggestion: The dark mode theme color contrast can be improved. as we have a lot of FAQ on screen that might create UI experience issue. 
you can start working on it, I assigned the task to you. meanwhile we can discuss dark mode colors. ( Its the problem with yellow and pitch dark )

**Comment by sau-mili** [comment]
![image](https://github.com/girlscript/gssoc-website-new/assets/146661411/ac494944-6945-440d-b72e-6723b39f0323)

**Comment by sanjay-kv** [comment]
this works @sau-mili

**Comment by sau-mili** [comment]
@sanjay-kv  can you check the PR?
