### ISSUE TITLE
Profile-Leaderboard Improvement

### ISSUE THREAD

**Issue by sanjay-kv** [girlscript/gssoc-website-new#293]
![image](https://github.com/girlscript/gssoc-website-new/assets/30715153/f06fc7a1-012d-426a-9fd7-d4795ff92839)

**Comment by n-keerthi-gayathri** [comment]
@sanjay-kv can you please explain me in detail about this issue?

**Comment by Ayushmaanagarwal1211** [comment]
Sir if you allow me i want to work on that and also please tell the changes you want

**Comment by sanjay-kv** [comment]
this is already person working on it. i just created issue to keep track of the progress.

**Comment by partha120804** [comment]
is someone still working on it ? @sanjay-kv

**Comment by sanjay-kv** [comment]
No, you can take lead

**Comment by Ayushmaanagarwal1211** [comment]
@sanjay-kv  Sir to get the details of every pr done by the user i am using an API of github but it will give limited API calls because if user have 100 pr so i need to fetch the details of 100 PR's so should i use that

**Comment by sanjay-kv** [comment]
Let me check this out .

**Comment by partha120804** [comment]
@sanjay-kv this was the one with devxprite (or something like that), that user have created an awesome page, what about that, were there any particular issues with that ??

**Comment by sanjay-kv** [comment]
Yes, his code crashes website couldn't provide sol.

**Comment by partha120804** [comment]
oh, can I work around with his implementation to see if I can make it work ?

**Comment by sanjay-kv** [comment]
Sure
