### ISSUE TITLE
The content is not visible in events page

### ISSUE THREAD

**Issue by manikumarreddyu** [girlscript/gssoc-website-new#299]
<img width="492" alt="image" src="https://github.com/girlscript/gssoc-website-new/assets/133508962/313481e0-3100-44e6-ac38-89a61f89b272">
<img width="470" alt="image" src="https://github.com/girlscript/gssoc-website-new/assets/133508962/44fc9327-d0c0-4c2a-a52a-d0f53856963b">
<img width="449" alt="image" src="https://github.com/girlscript/gssoc-website-new/assets/133508962/c118522e-bf48-467b-957c-2ac1da5b2d2d">

/assign

**Comment by sanjay-kv** [comment]
There is already team working on the overall site responsive. so I will be closing this issue.
