### ISSUE TITLE
Adding code of Conduct: WOB

### ISSUE THREAD

**Issue by sanjay-kv** [girlscript/gssoc-website-new#313]
![image](https://github.com/girlscript/gssoc-website-new/assets/30715153/c5432a32-b031-409b-8363-24f08ee4f10d)
You can see we have similalr code of conduct page for gssoc. 
https://gssoc.girlscript.tech/codeofconduct @Hemu21 

Use the same style for wob page and create contents with 
https://docs.google.com/document/d/1A_56b9BKkOcAzVvKf3ezwtrl69MrU3Otn7NZ-QfGkYw/edit#heading=h.6a6893tb8qvi

link to the new footer code of conduct. 

- [ ] New Page for WOB named code of conduct.
- [ ] Add the contents in the docs. 
- [ ] Request PR

**Comment by Hemu21** [comment]
@sanjay-kv ok can you please assign me
