### ISSUE TITLE
Add Animation on main page

### ISSUE THREAD

**Issue by heli0707** [girlscript/gssoc-website-new#317]
**Description**

To add animation to text on your main page, put the text you want to animate inside a special container. Then, set up a set of instructions that make the text move or change in a specific way. This will make the text appear with the desired effect when someone visits your page.

**Video**

https://github.com/girlscript/gssoc-website-new/assets/95361125/85de27b8-ca47-4656-8c6f-d7e90805168b

something like this

**Comment by heli0707** [comment]
@sanjay-kv  please assign this issue to me!

**Comment by sanjay-kv** [comment]
Np @heli0707 We are not looking to bring this change. I will be closing this issue now.
