### ISSUE TITLE
Sharing Badges

### ISSUE THREAD

**Issue by partha120804** [girlscript/gssoc-website-new#320]
Continued Issue #269 

@sanjay-kv I have successfully made it to paste the badge onto a template. ( I was facing issue for past 2 days because I was specifying the badge path wrong, as the path accessed by node are very confusing in this project and the error was very hard to troubleshoot)

Can you specify what information to provide on that template so that I can create a final template.

**Comment by partha120804** [comment]
@sanjay-kv will this do 
<img width="500" alt="image" src="https://github.com/girlscript/gssoc-website-new/assets/138643473/f06cbd72-1df4-4f4c-9436-c23d3de67f40">

the top red part will display name and profile picture of the contributor
the green area below the trophy will show the current points of the contributor
the blue area will show the name of the current badge.

**Comment by sanjay-kv** [comment]
This will do, I think it would be great if those blue green, red background not added. 

i will add one graphics designer from the team here. meanwhile we can implement the above. This is great feature.

**Comment by partha120804** [comment]
no no definitely not adding those red green boxes, i wasnt abble to draw on the pic to mark the areas so used those shapes instead

**Comment by partha120804** [comment]
![image](https://github.com/girlscript/gssoc-website-new/assets/138643473/01f3fdbc-794a-4053-89c1-a1ce59535d04)

I am trying to make the final output look something like this

**Comment by sanjay-kv** [comment]
this is awesome.
