### ISSUE TITLE
Issues and Bugs on GSSoC FAQ Page

### ISSUE THREAD

**Issue by MastanSayyad** [girlscript/gssoc-website-new#324]
Hey @sanjay-kv 

The **FAQ page** on the **GSSoC** official website has several issues and bugs that need to be addressed for a better user experience. 
Below are the detailed observations:

### > Theme Inconsistency

After refreshing the page, the FAQ section (Accordion only) switches to dark mode while other components remain in light mode. This inconsistency in theming can be confusing for users leading to **bad UI/UX**

https://github.com/user-attachments/assets/29a390c9-6788-4eaf-a0e4-0d5e1141e8f9

### > FAQ Accordion Functionality
The FAQ accordions do not close automatically when a new question is clicked. This makes navigation hard to handle as multiple answers remain open simultaneously.

https://github.com/user-attachments/assets/3386523c-d74f-417a-9a83-6e5cabf15c2d

### > Color Contrast

The font color for answers in light mode is yellow on an orange background, causing readability issues due to poor contrast.
(personally, it irritates my eyes and feels odd), 
The FAQ section could benefit from improved visual consistency in question formatting.

![image](https://github.com/user-attachments/assets/4cca7273-c655-4fa9-8ab0-a8507138c875)

### > Redundant Questions and Outdated Information

- There are duplicate questions about boys' participation.
- Some references are to GSSoC '22 and '23. These should be updated to the current year.

### > Broken Links
The links are not clickable, We should Ensure all external links are functional. so that after clicking users can redirect to the pages

![image](https://github.com/user-attachments/assets/ceb71804-3a3a-4f92-b22a-ec78f60bc614)

### > Additional FAQs (If Any)

Adding more questions related to the application process, timeline, and mentor expectations. etc

Addressing these issues can significantly improve the user experience and interface consistency.
Could you please assign this issue to me?

**Comment by Suvraneel** [comment]
@MastanSayyad Are you working on this one?

> **For AA standards, regular text and images of text must meet a minimum contrast ratio of 4.5:1. For text sized 18pt, text sized 14pt and bolded, or iconography, text must meet a minimum contrast ratio of 3:1**

That yellow contrast indeed has bad accessibility due to poor color contrast. Pls work on this.

**Comment by MastanSayyad** [comment]
> @MastanSayyad Are you working on this one?
> 
> > **For AA standards, regular text and images of text must meet a minimum contrast ratio of 4.5:1. For text sized 18pt, text sized 14pt and bolded, or iconography, text must meet a minimum contrast ratio of 3:1**
> 
> That yellow contrast indeed has bad accessibility due to poor color contrast. We need this fix.

Yes, I'm currently working on it, will fix it soon!
