### ISSUE TITLE
More Feature to personalised dashboard

### ISSUE THREAD

**Issue by sanjay-kv** [girlscript/gssoc-website-new#327]
Refer to this issue. 
https://github.com/girlscript/gssoc-website-new/pull/326
once he fix the issue anyone can workaround this

it would be great if you can bring components from the below page to show overall stat and badge they got.
https://gssoc.devxprite.tech/user/aditya-bhaumik

![screencapture-gssoc-devxprite-tech-user-aditya-bhaumik-2024-07-20-15_21_22](https://github.com/user-attachments/assets/0bf27a95-917f-43e7-b869-288c31d1f718)

**Comment by hars-21** [comment]
Please assign it to me! I'll work on it and will update you soon. 
For the UI part, should I copy the full design or you want only some component to be same from the website provided.
