### ISSUE TITLE
WOB Team Page Update

### ISSUE THREAD

**Issue by sanjay-kv** [girlscript/gssoc-website-new#337]
@Hemu21

Details.pdf](https://github.com/user-attachments/files/16343455/_Details.pdf)
https://gssoc.girlscript.tech/wobTeam

add your name right after program manager: and photo and titiel saying website developer

**Comment by nehal-5** [comment]
![IMG_20240518_175944](https://github.com/user-attachments/assets/55143b91-cb51-4650-9b08-7ece998d865b)
UI/UX Designer

**Comment by sanjay-kv** [comment]
need your github, linkedin, twitter link as well @nehal-5

**Comment by Hemu21** [comment]
Name - Hemanth Kumar
Designation - Web Developer
LinkedIn - https://www.linkedin.com/in/hemu21
GitHub - https://github.com/Hemu21
Twitter or X - https://x.com/Hemu21_
Image- https://drive.google.com/file/d/10HcpjFYU30EVrVAfxzQj1Y1eRx9l6nRn/view?usp=sharing


@sanjay-kv  is it ok?

**Comment by sanjay-kv** [comment]
yes

**Comment by nehal-5** [comment]
> > ![IMG_20240518_175944](https://private-user-images.githubusercontent.com/130452338/351179692-55143b91-cb51-4650-9b08-7ece998d865b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3MjcwODMsIm5iZiI6MTcyMTcyNjc4MywicGF0aCI6Ii8xMzA0NTIzMzgvMzUxMTc5NjkyLTU1MTQzYjkxLWNiNTEtNDY1MC05YjA4LTdlY2U5OThkODY1Yi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyM1QwOTI2MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZDExYTFmMmY0OTgyOTFiYTQ5OGM3YzU4NGU4MzQyZWQ2OGQ2OTgxMzRkYjg1ZmRkN2Y4NDU4ZTkzYzE1NjUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-z9R2U7TRB9aY6NFnlssyqJ_aenbj9-R9RpQS4L6lS0) UI/UX Designer Github: https://github.com/nehal-5 Linkedin: https://www.linkedin.com/in/nehal-fathema X: https://x.com/fathema_nehal?t=k60HeN5jzK5QJGfMJ02SMA&s=09
> 
> @nehal-5 can you please upload the image in your drive and provide the drive link. make sure the access.

Sure!

**Comment by Prithwi32** [comment]
Name - Prithwi Gajanan Hegde 
Designation - UI/UX Designer 
LinkedIn - https://www.linkedin.com/in/prithwi-hegde
GitHub - https://github.com/Prithwi32
Twitter or X - https://x.com/PrithwiHegde
Image - [link](https://drive.google.com/file/d/1YgFRndsN1yif-0b_oIlqgzS7zY8-q5ZC/view?usp=drivesdk)
