### ISSUE TITLE
WOB Page Updates

### ISSUE THREAD

**Issue by sanjay-kv** [girlscript/gssoc-website-new#349]
@sowmiyeh Can you specify the details here

**Comment by Hemu21** [comment]
@sanjay-kv  can you please assign me if sawmiyeh specify the details

**Comment by sanjay-kv** [comment]
sure

**Comment by sowmiyeh** [comment]
Requirements for WoB Page Updates:
 
- [ ] 1. https://gssoc.girlscript.tech/wobEvents - Need to update an event that the WoB Team did - https://www.youtube.com/live/V53unQsIISk?si=mRGHlErhNCV_sNP1 and remove duplicates 

- [ ] 2. Create Nav pages similar to GSSoC website: 
   - SPONSORS
   - JOB FAIR
   - FAQ
   - BLOG
   - CONTACT
   - SOCIALS
   - More: 
     - Code of Conduct
     - How WoB works?
     - Verify Certifications
    

- [ ] 3. Update the dates as 25th September - 25th November
- [ ] 4. Be a part of us in landing page should be edited as cards as in GSSoC for Contributors, project admin and mentors
- [ ] 5. Pop-Up screen for HackWeb3Conf - https://dorahacks.io/hackathon/hack-web3conf-24/ has to be added parallel with  Postman 
- [ ] 6. Update Team Page with Social Media Managers

For further details please tag me to get to know more supporting details

**Comment by sanjay-kv** [comment]
![image](https://github.com/user-attachments/assets/20edc2b7-d4eb-49a4-a7d3-1623db8e4418)

- [ ] Be a part of us in landing page should be edited as cards as in GSSoC for Contributors, project admin and mentors
![image](https://github.com/user-attachments/assets/503246b0-624f-4053-92aa-8bdcf702f5b0)

**Comment by Hemu21** [comment]
@sanjay-kv  @sowmiyeh   can you please provide the wob apply as contributor, mentor, project admin, sponsor links

**Comment by sanjay-kv** [comment]
i will reach out to sowmiya on this

**Comment by Hemu21** [comment]
@sanjay-kv  above said everything is updated. if you want i can make separete popups for wob and gssoc.

**Comment by sanjay-kv** [comment]
@Hemu21 Thanks. its alright, we can keep the same pop on both

**Comment by sowmiyeh** [comment]
@sanjay-kv Could you please assign this to someone in the team?

Timeline / Schedule

- Contributor, Mentor, Project admin email batch 1 ( 14 August)
- Contributor, Mentor, Project admin email batch 2 ( 30th August)
- Contributor, Mentor, Project admin email batch 3 ( 15th September)
- Project assign to mentors (23, 24th September)
- coding period start (25th September)
- community bonding period start (1st October)
- leaderboard open (10th October)
- Results announced (20th November)
- Coding period end (25th November)

**Comment by Hemu21** [comment]
@sowmiyeh ok will update
