### ISSUE TITLE
Hackweb3 Conf: Details

### ISSUE THREAD

**Issue by sanjay-kv** [girlscript/gssoc-website-new#368]
Links to redirect: 
any relevant approved images: 
Form link:

**Comment by sowmiyeh** [comment]
> Links to redirect: https://dorahacks.io/hackathon/hack-web3conf-24/detail
> any relevant approved images: Take the image from https://twitter.com/web3conf_india/status/1810701280555516326/photo/1
> Form link: https://dorahacks.io/hackathon/hack-web3conf-24/detail

**Comment by sanjay-kv** [comment]
@sowmiyeh both the url you provided is same.

**Comment by sowmiyeh** [comment]
> @sowmiyeh both the url you provided is same.

Yes you can use the same for both

**Comment by sanjay-kv** [comment]
@Hemu21 if that the case only register button is needed
