### ISSUE TITLE
List Open Issues of GSSoC22 Projects

### ISSUE THREAD

**Issue by BRAVO68WEB** [girlscript/gssoc-website-new#72]
## Idea

How about create a page list all the Issues tagged with "GSSoC22" and are unassigned.

## Why?
This will help mentees to browser all open issues of all participating repos and projects

We can implement sort by level, repo-name, createdOn,  lang, etc..

## Extras
PS: I can help in Backend and integration. Need help for UI and Frontend

**Comment by Suvraneel** [comment]
@BRAVO68WEB I have really considered this but tbh there's a lot of gray area there...
For eg, even contributors can create issues... The api will tag them as unassigned...

We could have done it by declaring a special label that PAs/mentors could add (say, `Up-for-Grabs` or `Open`)
But considering the already confused people with the score labeling system... I'm keeping this on hold...

**Comment by Suvraneel** [comment]
Honestly, in a large-scale program like this, we sometimes need to prioritize user-friendliness/convenience over functionality/cool features... We're still in the process of solving redundant tickets & calling PA/mentors up to let them know of the label-based scoring system & label-guidelines

**Comment by BRAVO68WEB** [comment]
Yeah, It could have been as great feature. But keeping in mind the doubts from current state, I know it could be really messy. Maybe next time ... right?

**Comment by Suvraneel** [comment]
@BRAVO68WEB  Yep exactly... 🚀
