### ISSUE TITLE
Search bar for Leaderboard

### ISSUE THREAD

**Issue by GaganpreetKaurKalsi** [girlscript/gssoc-website-new#74]
I am a Gssoc contributor 2022.

I was searching for my name in the leaderboard and was completely lost in there. I had to **Ctrl+F** my name at last to find it. It would be better if we can add a **search bar** in it for user ease. Let me know your views on the **new feature**. 

Also I would be happy to work on it.
Thanks!

**Comment by Suvraneel** [comment]
@GaganpreetKaurKalsi 
Yes, go ahead :octocat: 💯

**Comment by GaganpreetKaurKalsi** [comment]
Thanks @Suvraneel
Will make PR latest by today evening 👍
