### ISSUE TITLE
Loader for the leaderboard page

### ISSUE THREAD

**Issue by GaganpreetKaurKalsi** [girlscript/gssoc-website-new#76]
**Would like to propose following features : -**
1. Loader for the leaderboard page before data gets fetched.
2. Loader for the leaderboard table everytime search is made or data is changed.
3. Would also try to show message if no user exist for the particular name searched.
4. Custom messages in case of server is updating or data is not fetched.

**Comment by Suvraneel** [comment]
@GaganpreetKaurKalsi  🚀 Sure ! Go ahead :octocat: 

Optional: Like I said before, see if you can also add some confetti ... 
Resources for the same:    https://www.npmjs.com/package/react-confetti  OR   https://confetti.js.org/#

**Comment by GaganpreetKaurKalsi** [comment]
> @GaganpreetKaurKalsi 🚀 Sure ! Go ahead :octocat:
> 
> Optional: Like I said before, see if you can also add some confetti ... Resources for the same: https://www.npmjs.com/package/react-confetti OR https://confetti.js.org/#

Yeah did that! Half work is done. Just adding loader to the leaderboard table. It looks really cool to me. Right now the code is pretty much commented. Will share video soon.

**Comment by GaganpreetKaurKalsi** [comment]
Hey **@Suvraneel** :octocat: 
Have a look at the video and let me know if it looks good. My browser is pretty shaky right now so you might find a little lag in the video.
https://user-images.githubusercontent.com/54144759/163796040-4b8350bb-7ddc-4102-8e2f-00fb593007f5.mp4

**Comment by Suvraneel** [comment]
@GaganpreetKaurKalsi   Looks pretty kewlllll 🔥 

Don't worry I always run the code myself across different browser builds & viewports for compatibility issues...
Looks noice... Make the PR
