### ISSUE TITLE
Enhancements to makeshift pages under `More` for GSSoC 2023 :octocat: 

### ISSUE THREAD

**Issue by Suvraneel** [girlscript/gssoc-website-new#85]
- `How they do?` section in `How GSSoC works?` page... Replace images with responsive web elements , also improve guidelines (lots of typos & procedure gap exists)

- Add yearly triggers (ie, hooks like in `Team` page) in both `Events` & `Campus Ambassadors` pages as a credit to all CAs & speakers who've contributed towards making the program this successful...

- Also, Improve UI of `Events` page if you can... 
& categorisation of `Blog` page

**Comment by NageshMandal** [comment]
I want to work on this issue. Could you please assign it to me.

**Comment by Suvraneel** [comment]
- `How they do?` section in `How GSSoC works?` page... Replace images with responsive web elements , also improve guidelines (lots of typos & procedure gap exists)

Feel free to contribute @NageshMandal 

You'll be working on/modifying the following file only:
`pages > info.js`    

Prioritise usage of TailwindCSS. But if needed, you may add any extra required css in `styles > globals.css`

**Comment by mohdhaider07** [comment]
Assign this to me @Suvraneel

**Comment by Suvraneel** [comment]
@mohdhaider07  
Noice. 1st contributor for GSSoC'23?
Sure, go ahead. All the best. Lemme know if you need any clarifications
